### PR TITLE
[R-package] Fix build_r.R failing in Windows

### LINKED ISSUE #1693: [R-package] build_r.R fails in Windows
With Windows and MinGW, build_r.R fails with the following error:

```
$ Rscript build_r.R
Error: Can't find 'E:\sandbox\LightGBM\lightgbm_r\'.
Execution halted
```

### PR DESCRIPTION
**Pull request by Laurae2**
Fixes #1693

### CODE REVIEW

File: build_r.R [hunk 1]
```diff
@@ -1,4 +1,4 @@
-# for macOS users who have decided to use gcc
+# Fr macOS users who have decided to use gcc
```
Comment (StrikerRUS) [inline build_r.R]: **For**

File: build_r.R [hunk 2]
```diff
@@ -7,76 +7,63 @@
...
 
-result <- file.copy(
-    from = "CMakeLists.txt"
-    , to = file.path("lightgbm_r", "inst", "bin/")
-    , recursive = TRUE
-    , overwrite = TRUE
-)
+result <- file.copy(from = "CMakeLists.txt",
+                    to = file.path("lightgbm_r", "inst", "bin/"),
+                    overwrite = TRUE)
```
Comment (jameslamb) [inline build_r.R]: is this what was causing the problem? (looks like you removed the `recursive = TRUE`)

A lot of these are formatting changes, so trying to find whichever thing was causing the issue

Comment (Laurae2) [reply build_r.R]: I had two errors:

* on `devtools::document(pkg = "lightgbm_r/")` (because of the trailing slash)
* on the file with recursive (it causes a warning, which causes an error when R is setup to throw an error on warnings)

**Comment by Laurae2** [comment]
@jameslamb Do you have the rights to delete the branch fix-#1693 ? It seems I cannot delete it anymore (getting GitHub 404 error).

**Comment by jameslamb** [comment]
Thanks @StrikerRUS !
