### PR TITLE
fix R crash problem.

### LINKED ISSUE #771: Crash in R-package due to bad parameters
R-package systematically crashes when passing bad parameters to LightGBM.

Code for reproducible crash:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

# Workaround...
dtrain$construct()
dtest$construct()

# CRASH
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10,
                   aaaaaaaaaa = 1)
```

Surprisingly, this does not crash but the issue cannot be fixed without `lgb.unloader(wipe = TRUE)`:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label, aaaaaaaaaa = 1) # Attempt to crash here
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

# Attempt to crash again, does not crash
dtrain$construct()
dtest$construct()

# Does not crash
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)

# Attempt to fix the problem, fails
dtrain <- lgb.Dataset(train$data, label = train$label)
dtrain$construct()
dtest$construct()

# Fix problem
lgb.unloader(wipe = TRUE)
library(lightgbm)
dtrain <- lgb.Dataset(train$data, label = train$label)
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
valids <- list(test = dtest)
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)
```

### PR DESCRIPTION
**Pull request by guolinke**
fix #771 .

### CODE REVIEW

File: R-package/R/utils.R [hunk 1]
```diff
@@ -6,13 +6,8 @@ lgb.is.Dataset <- function(x) {
   lgb.check.r6.class(x, "lgb.Dataset") # Checking if it is of class lgb.Dataset or not
 }
 
-# use 64bit data to store address
-lgb.new.handle <- function() {
-  0.0 # Return numeric type in R
```
Comment (guolinke) [inline R-package/R/utils.R]: @Laurae2 when using this function to allocate a zero pointer, it sometimes will get some strange values. This causes the incorrect result when calling lgb.is.null.handle .

File: R-package/R/utils.R [hunk 2]
```diff
@@ -25,20 +20,19 @@ lgb.encode.char <- function(arr, len) {
...
   if (!is.null(ret)) {
     call_state <- .Call(fun_name, ..., ret, call_state, PACKAGE = "lib_lightgbm") # Call with ret
   } else {
     call_state <- .Call(fun_name, ..., call_state, PACKAGE = "lib_lightgbm") # Call without ret
   }
-  
+  call_state <- as.integer(call_state)
   # Check for call state value post call
   if (call_state != 0L) {
-
```
Comment (guolinke) [inline R-package/R/utils.R]: the scripts inside this scope is delay to call.  I am confused by R running order.

**Comment by Laurae2** [comment]
@guolinke it does not crash anymore and it can even run after an error during training / building dataset when in the past we needed `lgb.unloader`:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

# Workaround...
dtrain$construct()
dtest$construct()

# NO MORE CRASH
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10,
                   aaaaaaaaaa = 1)

# Can run correctly without lgb.unloader
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)
```

File: R-package/R/utils.R (hunk 1 above)
Comment (Laurae2) [inline R-package/R/utils.R]: When using C/C++ in R, it is possible to read/write memory of R. It is possible LightGBM writes in R memory when it should not.

File: R-package/R/utils.R (hunk 2 above)
Comment (Laurae2) [inline R-package/R/utils.R]: @guolinke I think it runs only for creating dataset (if free handle, to store handle, and to create dataset (twice?) ).

It should run synchronous, does it run currently asynchronous?

Comment (guolinke) [inline R-package/R/utils.R]: yeah, you can add ```print(call_state != 0L)``` before this line, and run your scripts (the test of crash). And when it is true, the following scripts inside this scope are not call. it will continue run to here (https://github.com/Microsoft/LightGBM/blob/fix-r/R-package/R/lgb.Booster.R#L96) then stop.

Comment (guolinke) [inline R-package/R/utils.R]: I will merge this PR first. Can you help to investigate this issue ?

Comment (Laurae2) [inline R-package/R/utils.R]: @guolinke Is it this line?

https://github.com/Microsoft/LightGBM/blob/master/R-package/R/lgb.Booster.R#L96 (your link is pointing to a dead page)

Comment (guolinke) [inline R-package/R/utils.R]: Yeah

Comment (Laurae2) [inline R-package/R/utils.R]: Check https://github.com/Microsoft/LightGBM/issues/795 for where is the error and the synchronous call chain.
