### PR TITLE
re-order includes (fixes #3132)

### LINKED ISSUE #3132: [ci] New cpplint warning: C++ header after another system header
I started seeing warnings like this on Travis today ([example build](https://travis-ci.org/github/microsoft/LightGBM/jobs/693187886))

> include/LightGBM/boosting.h:11:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/boosting.h:12:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/boosting.h:13:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/boosting.h:14:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]

<details><summary>320 errors!</summary>

```
Linting C++ code
src/network/socket_wrapper.hpp:11:  Found C++ system header after other system header. Should be: socket_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
src/network/socket_wrapper.hpp:12:  Found C++ system header after other system header. Should be: socket_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
src/network/socket_wrapper.hpp:13:  Found C++ system header after other system header. Should be: socket_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
src/network/socket_wrapper.hpp:14:  Found C++ system header after other system header. Should be: socket_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/network/socket_wrapper.hpp
src/objective/multiclass_objective.hpp:11:  Found C++ system header after other system header. Should be: multiclass_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/multiclass_objective.hpp:12:  Found C++ system header after other system header. Should be: multiclass_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/multiclass_objective.hpp:13:  Found C++ system header after other system header. Should be: multiclass_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/multiclass_objective.hpp:14:  Found C++ system header after other system header. Should be: multiclass_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/multiclass_objective.hpp:15:  Found C++ system header after other system header. Should be: multiclass_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/multiclass_objective.hpp:16:  Found C++ system header after other system header. Should be: multiclass_objective.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/objective/multiclass_objective.hpp
Done processing src/boosting/boosting.cpp
src/io/json11.cpp:25:  Found C++ system header after other system header. Should be: json11.h, c system, c++ system, other.  [build/include_order] [4]
src/io/json11.cpp:26:  Found C++ system header after other system header. Should be: json11.h, c system, c++ system, other.  [build/include_order] [4]
src/io/json11.cpp:27:  Found C++ system header after other system header. Should be: json11.h, c system, c++ system, other.  [build/include_order] [4]
src/io/json11.cpp:28:  Found C++ system header after other system header. Should be: json11.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/json11.cpp
src/boosting/dart.hpp:10:  Found C++ system header after other system header. Should be: dart.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/dart.hpp:11:  Found C++ system header after other system header. Should be: dart.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/dart.hpp:12:  Found C++ system header after other system header. Should be: dart.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/dart.hpp:13:  Found C++ system header after other system header. Should be: dart.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/dart.hpp:14:  Found C++ system header after other system header. Should be: dart.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/dart.hpp
include/LightGBM/boosting.h:11:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/boosting.h:12:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/boosting.h:13:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/boosting.h:14:  Found C++ system header after other system header. Should be: boosting.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/boosting.h
src/c_api.cpp:21:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
src/c_api.cpp:22:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
src/c_api.cpp:23:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
src/c_api.cpp:24:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
src/c_api.cpp:25:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
src/c_api.cpp:26:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
src/c_api.cpp:27:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/c_api.cpp
include/LightGBM/feature_group.h:12:  Found C++ system header after other system header. Should be: feature_group.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/feature_group.h:13:  Found C++ system header after other system header. Should be: feature_group.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/feature_group.h:14:  Found C++ system header after other system header. Should be: feature_group.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/feature_group.h
src/boosting/score_updater.hpp:14:  Found C++ system header after other system header. Should be: score_updater.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/score_updater.hpp:15:  Found C++ system header after other system header. Should be: score_updater.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/score_updater.hpp
src/treelearner/gpu_tree_learner.cpp:13:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/gpu_tree_learner.cpp
src/treelearner/voting_parallel_tree_learner.cpp:7:  Found C++ system header after other system header. Should be: voting_parallel_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/voting_parallel_tree_learner.cpp:8:  Found C++ system header after other system header. Should be: voting_parallel_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/voting_parallel_tree_learner.cpp:9:  Found C++ system header after other system header. Should be: voting_parallel_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/voting_parallel_tree_learner.cpp
include/LightGBM/metric.h:15:  Found C++ system header after other system header. Should be: metric.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/metric.h:16:  Found C++ system header after other system header. Should be: metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/metric.h
include/LightGBM/dataset_loader.h:10:  Found C++ system header after other system header. Should be: dataset_loader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset_loader.h:11:  Found C++ system header after other system header. Should be: dataset_loader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset_loader.h:12:  Found C++ system header after other system header. Should be: dataset_loader.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/dataset_loader.h
src/metric/xentropy_metric.hpp:13:  Found C++ system header after other system header. Should be: xentropy_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/xentropy_metric.hpp:14:  Found C++ system header after other system header. Should be: xentropy_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/xentropy_metric.hpp:15:  Found C++ system header after other system header. Should be: xentropy_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/xentropy_metric.hpp:16:  Found C++ system header after other system header. Should be: xentropy_metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/xentropy_metric.hpp
src/treelearner/split_info.hpp:10:  Found C++ system header after other system header. Should be: split_info.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/split_info.hpp:11:  Found C++ system header after other system header. Should be: split_info.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/split_info.hpp:12:  Found C++ system header after other system header. Should be: split_info.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/split_info.hpp:13:  Found C++ system header after other system header. Should be: split_info.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/split_info.hpp:14:  Found C++ system header after other system header. Should be: split_info.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/split_info.hpp:15:  Found C++ system header after other system header. Should be: split_info.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/split_info.hpp
src/treelearner/gpu_tree_learner.h:14:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/gpu_tree_learner.h:15:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/gpu_tree_learner.h:16:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/gpu_tree_learner.h:17:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/gpu_tree_learner.h:18:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/gpu_tree_learner.h:19:  Found C++ system header after other system header. Should be: gpu_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/gpu_tree_learner.h
src/objective/binary_objective.hpp:11:  Found C++ system header after other system header. Should be: binary_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/binary_objective.hpp:12:  Found C++ system header after other system header. Should be: binary_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/binary_objective.hpp:13:  Found C++ system header after other system header. Should be: binary_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/binary_objective.hpp:14:  Found C++ system header after other system header. Should be: binary_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/binary_objective.hpp:15:  Found C++ system header after other system header. Should be: binary_objective.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/objective/binary_objective.hpp
Done processing src/boosting/gbdt_prediction.cpp
include/LightGBM/objective_function.h:12:  Found C++ system header after other system header. Should be: objective_function.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/objective_function.h:13:  Found C++ system header after other system header. Should be: objective_function.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/objective_function.h
include/LightGBM/utils/array_args.h:11:  Found C++ system header after other system header. Should be: array_args.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/array_args.h:12:  Found C++ system header after other system header. Should be: array_args.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/array_args.h:13:  Found C++ system header after other system header. Should be: array_args.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/utils/array_args.h
src/metric/multiclass_metric.hpp:11:  Found C++ system header after other system header. Should be: multiclass_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/multiclass_metric.hpp:12:  Found C++ system header after other system header. Should be: multiclass_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/multiclass_metric.hpp:13:  Found C++ system header after other system header. Should be: multiclass_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/multiclass_metric.hpp:14:  Found C++ system header after other system header. Should be: multiclass_metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/multiclass_metric.hpp
Done processing src/treelearner/feature_parallel_tree_learner.cpp
include/LightGBM/bin.h:12:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/bin.h:13:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/bin.h:14:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/bin.h:15:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/bin.h:16:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/bin.h:17:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/bin.h
src/boosting/goss.hpp:12:  Found C++ system header after other system header. Should be: goss.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/goss.hpp:13:  Found C++ system header after other system header. Should be: goss.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/goss.hpp:14:  Found C++ system header after other system header. Should be: goss.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/goss.hpp:15:  Found C++ system header after other system header. Should be: goss.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/goss.hpp:16:  Found C++ system header after other system header. Should be: goss.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/goss.hpp:17:  Found C++ system header after other system header. Should be: goss.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/goss.hpp
Done processing src/network/linkers_mpi.cpp
include/LightGBM/utils/common.h:11:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:12:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:13:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:14:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:15:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:16:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:17:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:18:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:19:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:20:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:21:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:22:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:23:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:24:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:25:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:26:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/common.h:27:  Found C++ system header after other system header. Should be: common.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/utils/common.h
src/boosting/gbdt_model_text.cpp:11:  Found C++ system header after other system header. Should be: gbdt_model_text.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt_model_text.cpp:12:  Found C++ system header after other system header. Should be: gbdt_model_text.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt_model_text.cpp:13:  Found C++ system header after other system header. Should be: gbdt_model_text.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/gbdt_model_text.cpp
src/metric/binary_metric.hpp:12:  Found C++ system header after other system header. Should be: binary_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/binary_metric.hpp:13:  Found C++ system header after other system header. Should be: binary_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/binary_metric.hpp:14:  Found C++ system header after other system header. Should be: binary_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/binary_metric.hpp:15:  Found C++ system header after other system header. Should be: binary_metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/binary_metric.hpp
src/boosting/rf.hpp:11:  Found C++ system header after other system header. Should be: rf.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/rf.hpp:12:  Found C++ system header after other system header. Should be: rf.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/rf.hpp:13:  Found C++ system header after other system header. Should be: rf.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/rf.hpp:14:  Found C++ system header after other system header. Should be: rf.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/rf.hpp:15:  Found C++ system header after other system header. Should be: rf.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/rf.hpp:16:  Found C++ system header after other system header. Should be: rf.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/rf.hpp
src/network/linker_topo.cpp:9:  Found C++ system header after other system header. Should be: linker_topo.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linker_topo.cpp:10:  Found C++ system header after other system header. Should be: linker_topo.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linker_topo.cpp:11:  Found C++ system header after other system header. Should be: linker_topo.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/network/linker_topo.cpp
src/treelearner/leaf_splits.hpp:10:  Found C++ system header after other system header. Should be: leaf_splits.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/leaf_splits.hpp:11:  Found C++ system header after other system header. Should be: leaf_splits.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/leaf_splits.hpp
src/io/dataset.cpp:13:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
src/io/dataset.cpp:14:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
src/io/dataset.cpp:15:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
src/io/dataset.cpp:16:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
src/io/dataset.cpp:17:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/dataset.cpp
Done processing src/metric/metric.cpp
include/LightGBM/c_api.h:18:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/c_api.h:19:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/c_api.h:20:  Found C++ system header after other system header. Should be: c_api.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/c_api.h
include/LightGBM/utils/text_reader.h:12:  Found C++ system header after other system header. Should be: text_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/text_reader.h:13:  Found C++ system header after other system header. Should be: text_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/text_reader.h:14:  Found C++ system header after other system header. Should be: text_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/text_reader.h:15:  Found C++ system header after other system header. Should be: text_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/text_reader.h:16:  Found C++ system header after other system header. Should be: text_reader.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/utils/text_reader.h
Done processing R-package/src/lightgbm_R.h
src/io/config.cpp:11:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/config.cpp
src/application/predictor.hpp:14:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:15:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:16:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:17:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:18:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:19:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:20:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:21:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
src/application/predictor.hpp:22:  Found C++ system header after other system header. Should be: predictor.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/application/predictor.hpp
src/io/bin.cpp:11:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/bin.cpp:12:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/bin.cpp:13:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/bin.cpp:14:  Found C++ system header after other system header. Should be: bin.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/bin.cpp
include/LightGBM/dataset.h:15:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset.h:16:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset.h:17:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset.h:18:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset.h:19:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset.h:20:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/dataset.h:21:  Found C++ system header after other system header. Should be: dataset.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/dataset.h
include/LightGBM/prediction_early_stop.h:10:  Found C++ system header after other system header. Should be: prediction_early_stop.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/prediction_early_stop.h:11:  Found C++ system header after other system header. Should be: prediction_early_stop.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/prediction_early_stop.h
src/application/application.cpp:18:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:19:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:20:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:21:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:22:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:23:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:24:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/application/application.cpp
src/objective/xentropy_objective.hpp:12:  Found C++ system header after other system header. Should be: xentropy_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/xentropy_objective.hpp:13:  Found C++ system header after other system header. Should be: xentropy_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/xentropy_objective.hpp:14:  Found C++ system header after other system header. Should be: xentropy_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/xentropy_objective.hpp:15:  Found C++ system header after other system header. Should be: xentropy_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/xentropy_objective.hpp:16:  Found C++ system header after other system header. Should be: xentropy_objective.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/objective/xentropy_objective.hpp
src/objective/rank_objective.hpp:12:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/rank_objective.hpp:13:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/rank_objective.hpp:14:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/rank_objective.hpp:15:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/rank_objective.hpp:16:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/rank_objective.hpp:17:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/rank_objective.hpp:18:  Found C++ system header after other system header. Should be: rank_objective.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/objective/rank_objective.hpp
Done processing include/LightGBM/utils/log.h
Done processing R-package/src/R_object_helper.h
src/metric/dcg_calculator.cpp:8:  Found C++ system header after other system header. Should be: dcg_calculator.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/dcg_calculator.cpp:9:  Found C++ system header after other system header. Should be: dcg_calculator.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/dcg_calculator.cpp:10:  Found C++ system header after other system header. Should be: dcg_calculator.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/dcg_calculator.cpp
include/LightGBM/tree.h:11:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/tree.h:12:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/tree.h:13:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/tree.h:14:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/tree.h:15:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/tree.h
src/io/metadata.cpp:8:  Found C++ system header after other system header. Should be: metadata.h, c system, c++ system, other.  [build/include_order] [4]
src/io/metadata.cpp:9:  Found C++ system header after other system header. Should be: metadata.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/metadata.cpp
include/LightGBM/tree_learner.h:12:  Found C++ system header after other system header. Should be: tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/tree_learner.h:13:  Found C++ system header after other system header. Should be: tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/tree_learner.h
src/treelearner/data_partition.hpp:13:  Found C++ system header after other system header. Should be: data_partition.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/data_partition.hpp:14:  Found C++ system header after other system header. Should be: data_partition.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/data_partition.hpp:15:  Found C++ system header after other system header. Should be: data_partition.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/data_partition.hpp
src/io/file_io.cpp:10:  Found C++ system header after other system header. Should be: file_io.h, c system, c++ system, other.  [build/include_order] [4]
src/io/file_io.cpp:11:  Found C++ system header after other system header. Should be: file_io.h, c system, c++ system, other.  [build/include_order] [4]
src/io/file_io.cpp:12:  Found C++ system header after other system header. Should be: file_io.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/file_io.cpp
src/boosting/gbdt.cpp:14:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.cpp:15:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.cpp:16:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/gbdt.cpp
src/network/network.cpp:9:  Found C++ system header after other system header. Should be: network.h, c system, c++ system, other.  [build/include_order] [4]
src/network/network.cpp:10:  Found C++ system header after other system header. Should be: network.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/network/network.cpp
src/treelearner/cost_effective_gradient_boosting.hpp:13:  Found C++ system header after other system header. Should be: cost_effective_gradient_boosting.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/cost_effective_gradient_boosting.hpp
src/metric/regression_metric.hpp:11:  Found C++ system header after other system header. Should be: regression_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/regression_metric.hpp:12:  Found C++ system header after other system header. Should be: regression_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/regression_metric.hpp:13:  Found C++ system header after other system header. Should be: regression_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/regression_metric.hpp:14:  Found C++ system header after other system header. Should be: regression_metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/regression_metric.hpp
Done processing src/treelearner/tree_learner.cpp
include/LightGBM/application.h:11:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/application.h:12:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/application.h
src/io/multi_val_dense_bin.hpp:11:  Found C++ system header after other system header. Should be: multi_val_dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/multi_val_dense_bin.hpp:12:  Found C++ system header after other system header. Should be: multi_val_dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/multi_val_dense_bin.hpp:13:  Found C++ system header after other system header. Should be: multi_val_dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/multi_val_dense_bin.hpp:14:  Found C++ system header after other system header. Should be: multi_val_dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/multi_val_dense_bin.hpp
Done processing include/LightGBM/utils/json11.h
src/io/dense_bin.hpp:11:  Found C++ system header after other system header. Should be: dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/dense_bin.hpp:12:  Found C++ system header after other system header. Should be: dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/dense_bin.hpp:13:  Found C++ system header after other system header. Should be: dense_bin.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/dense_bin.hpp
Done processing src/io/config_auto.cpp
include/LightGBM/utils/openmp_wrapper.h:13:  Found C++ system header after other system header. Should be: openmp_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/openmp_wrapper.h:14:  Found C++ system header after other system header. Should be: openmp_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/openmp_wrapper.h:15:  Found C++ system header after other system header. Should be: openmp_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/openmp_wrapper.h:16:  Found C++ system header after other system header. Should be: openmp_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/openmp_wrapper.h:17:  Found C++ system header after other system header. Should be: openmp_wrapper.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/utils/openmp_wrapper.h
include/LightGBM/network.h:12:  Found C++ system header after other system header. Should be: network.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/network.h:13:  Found C++ system header after other system header. Should be: network.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/network.h:14:  Found C++ system header after other system header. Should be: network.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/network.h
src/boosting/prediction_early_stop.cpp:9:  Found C++ system header after other system header. Should be: prediction_early_stop.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/prediction_early_stop.cpp:10:  Found C++ system header after other system header. Should be: prediction_early_stop.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/prediction_early_stop.cpp:11:  Found C++ system header after other system header. Should be: prediction_early_stop.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/prediction_early_stop.cpp:12:  Found C++ system header after other system header. Should be: prediction_early_stop.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/prediction_early_stop.cpp
Done processing include/LightGBM/utils/random.h
Done processing include/LightGBM/utils/file_io.h
R-package/src/lightgbm_R.cpp:15:  Found C++ system header after other system header. Should be: lightgbm_R.h, c system, c++ system, other.  [build/include_order] [4]
R-package/src/lightgbm_R.cpp:16:  Found C++ system header after other system header. Should be: lightgbm_R.h, c system, c++ system, other.  [build/include_order] [4]
R-package/src/lightgbm_R.cpp:17:  Found C++ system header after other system header. Should be: lightgbm_R.h, c system, c++ system, other.  [build/include_order] [4]
R-package/src/lightgbm_R.cpp:18:  Found C++ system header after other system header. Should be: lightgbm_R.h, c system, c++ system, other.  [build/include_order] [4]
R-package/src/lightgbm_R.cpp:19:  Found C++ system header after other system header. Should be: lightgbm_R.h, c system, c++ system, other.  [build/include_order] [4]
R-package/src/lightgbm_R.cpp:20:  Found C++ system header after other system header. Should be: lightgbm_R.h, c system, c++ system, other.  [build/include_order] [4]
Done processing R-package/src/lightgbm_R.cpp
src/treelearner/serial_tree_learner.cpp:12:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.cpp:13:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.cpp:14:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.cpp:15:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/serial_tree_learner.cpp
src/io/parser.hpp:12:  Found C++ system header after other system header. Should be: parser.h, c system, c++ system, other.  [build/include_order] [4]
src/io/parser.hpp:13:  Found C++ system header after other system header. Should be: parser.h, c system, c++ system, other.  [build/include_order] [4]
src/io/parser.hpp:14:  Found C++ system header after other system header. Should be: parser.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/parser.hpp
Done processing src/treelearner/data_parallel_tree_learner.cpp
Done processing include/LightGBM/export.h
Done processing src/objective/objective_function.cpp
src/network/linkers.h:13:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers.h:14:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers.h:15:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers.h:16:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers.h:17:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers.h:18:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers.h:19:  Found C++ system header after other system header. Should be: linkers.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/network/linkers.h
src/io/sparse_bin.hpp:13:  Found C++ system header after other system header. Should be: sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/sparse_bin.hpp:14:  Found C++ system header after other system header. Should be: sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/sparse_bin.hpp:15:  Found C++ system header after other system header. Should be: sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/sparse_bin.hpp:16:  Found C++ system header after other system header. Should be: sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/sparse_bin.hpp:17:  Found C++ system header after other system header. Should be: sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/sparse_bin.hpp:18:  Found C++ system header after other system header. Should be: sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/sparse_bin.hpp
include/LightGBM/utils/threading.h:13:  Found C++ system header after other system header. Should be: threading.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/threading.h:14:  Found C++ system header after other system header. Should be: threading.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/threading.h:15:  Found C++ system header after other system header. Should be: threading.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/utils/threading.h
src/metric/map_metric.hpp:13:  Found C++ system header after other system header. Should be: map_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/map_metric.hpp:14:  Found C++ system header after other system header. Should be: map_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/map_metric.hpp:15:  Found C++ system header after other system header. Should be: map_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/map_metric.hpp:16:  Found C++ system header after other system header. Should be: map_metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/map_metric.hpp
include/LightGBM/utils/pipeline_reader.h:11:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/pipeline_reader.h:12:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/pipeline_reader.h:13:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/pipeline_reader.h:14:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/pipeline_reader.h:15:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/pipeline_reader.h:16:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/utils/pipeline_reader.h:17:  Found C++ system header after other system header. Should be: pipeline_reader.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/utils/pipeline_reader.h
src/main.cpp:7:  Found C++ system header after other system header. Should be: main.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/main.cpp
Done processing src/treelearner/monotone_constraints.hpp
src/metric/rank_metric.hpp:13:  Found C++ system header after other system header. Should be: rank_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/rank_metric.hpp:14:  Found C++ system header after other system header. Should be: rank_metric.h, c system, c++ system, other.  [build/include_order] [4]
src/metric/rank_metric.hpp:15:  Found C++ system header after other system header. Should be: rank_metric.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/metric/rank_metric.hpp
src/boosting/gbdt.h:14:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:15:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:16:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:17:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:18:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:19:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:20:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:21:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:22:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
src/boosting/gbdt.h:23:  Found C++ system header after other system header. Should be: gbdt.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/boosting/gbdt.h
src/treelearner/feature_histogram.hpp:13:  Found C++ system header after other system header. Should be: feature_histogram.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/feature_histogram.hpp:14:  Found C++ system header after other system header. Should be: feature_histogram.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/feature_histogram.hpp:15:  Found C++ system header after other system header. Should be: feature_histogram.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/feature_histogram.hpp:16:  Found C++ system header after other system header. Should be: feature_histogram.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/feature_histogram.hpp:17:  Found C++ system header after other system header. Should be: feature_histogram.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/feature_histogram.hpp:18:  Found C++ system header after other system header. Should be: feature_histogram.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/feature_histogram.hpp
src/io/tree.cpp:11:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
src/io/tree.cpp:12:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
src/io/tree.cpp:13:  Found C++ system header after other system header. Should be: tree.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/tree.cpp
src/objective/regression_objective.hpp:12:  Found C++ system header after other system header. Should be: regression_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/regression_objective.hpp:13:  Found C++ system header after other system header. Should be: regression_objective.h, c system, c++ system, other.  [build/include_order] [4]
src/objective/regression_objective.hpp:14:  Found C++ system header after other system header. Should be: regression_objective.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/objective/regression_objective.hpp
src/treelearner/parallel_tree_learner.h:11:  Found C++ system header after other system header. Should be: parallel_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/parallel_tree_learner.h:12:  Found C++ system header after other system header. Should be: parallel_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/parallel_tree_learner.h:13:  Found C++ system header after other system header. Should be: parallel_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/parallel_tree_learner.h
src/treelearner/serial_tree_learner.h:15:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.h:16:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.h:17:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.h:18:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.h:19:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/serial_tree_learner.h:20:  Found C++ system header after other system header. Should be: serial_tree_learner.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/serial_tree_learner.h
src/network/linkers_socket.cpp:11:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers_socket.cpp:12:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers_socket.cpp:13:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers_socket.cpp:14:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers_socket.cpp:15:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers_socket.cpp:16:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
src/network/linkers_socket.cpp:17:  Found C++ system header after other system header. Should be: linkers_socket.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/network/linkers_socket.cpp
src/treelearner/col_sampler.hpp:15:  Found C++ system header after other system header. Should be: col_sampler.h, c system, c++ system, other.  [build/include_order] [4]
src/treelearner/col_sampler.hpp:16:  Found C++ system header after other system header. Should be: col_sampler.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/treelearner/col_sampler.hpp
Done processing src/io/parser.cpp
src/io/dataset_loader.cpp:13:  Found C++ system header after other system header. Should be: dataset_loader.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/dataset_loader.cpp
include/LightGBM/config.h:19:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/config.h:20:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/config.h:21:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/config.h:22:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/config.h:23:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
include/LightGBM/config.h:24:  Found C++ system header after other system header. Should be: config.h, c system, c++ system, other.  [build/include_order] [4]
Done processing include/LightGBM/config.h
src/io/multi_val_sparse_bin.hpp:11:  Found C++ system header after other system header. Should be: multi_val_sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/multi_val_sparse_bin.hpp:12:  Found C++ system header after other system header. Should be: multi_val_sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/multi_val_sparse_bin.hpp:13:  Found C++ system header after other system header. Should be: multi_val_sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
src/io/multi_val_sparse_bin.hpp:14:  Found C++ system header after other system header. Should be: multi_val_sparse_bin.h, c system, c++ system, other.  [build/include_order] [4]
Done processing src/io/multi_val_sparse_bin.hpp
Done processing include/LightGBM/meta.h
Total errors found: 320
```

</summary>

It looks like there was a new `cpplint` release [today](https://pypi.org/project/cpplint/#history)

image

I'm going to try to fix these right now.  This will block all PRs until we fix it. If I can't fix it quickly,  we can always peg `cpplint==1.4.5`, but hopefully the fix won't take too long.

### PR DESCRIPTION
**Pull request by jameslamb**
See  #3132 for details. **The `lint` task in CI is broken right now** because of a new release to `cpplint` a  few hours ago. As of that release, `cpplint` now  enforces the Google style guide recommendations for how  `include`s should be ordered:

1. dir2/foo2.h.
2. A blank line
3. C system headers (more precisely: headers in angle brackets with the .h extension), e.g., <unistd.h>, <stdlib.h>.
4. A blank line
5. C++ standard library headers (without file extension), e.g., <algorithm>, <cstddef>.
6. A blank line
7. Other libraries' .h files.
8. Your project's .h files.

And the reason this is recommended:

> With the preferred ordering, if the related header dir2/foo2.h omits any necessary includes, the build of dir/foo.cc or dir/foo_test.cc will break. Thus, this rule ensures that build breaks show up first for the people working on these files, not for innocent people in other packages.

### CODE REVIEW

File: src/application/application.cpp [hunk 1]
```diff
@@ -2,6 +2,15 @@
...
+
+#include <string>
+#include <chrono>
+#include <cstdio>
+#include <ctime>
+#include <fstream>
+#include <sstream>
+#include <utility>
+
 #include <LightGBM/application.h>
```
Comment (StrikerRUS) [inline src/application/application.cpp:14]: According to the Google style, `LightGBM/application.h` (the same issue with the most `cpp` files from this PR) should be the first one. Is there a bug in `cpplint` which blocks us from using the correct order? Refer to https://github.com/microsoft/LightGBM/pull/2066#issue-263709049.

Comment (jameslamb) [reply src/application/application.cpp:14]: Oh thanks, I didn't know about #2066!

Yes, if I move just `LightGBM/application.h` back to the top and leave everything else the same in this PR, I get this from `cpplint`

> src/application/application.cpp:8:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:9:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:10:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:11:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:12:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:13:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]
src/application/application.cpp:14:  Found C++ system header after other system header. Should be: application.h, c system, c++ system, other.  [build/include_order] [4]

I think it is probably because this is called `application/application.cpp` and `cpplint` is expecting to find `"application.h"` (header colocated with implementation). When I change `<LightGBM/application.h>` to `"application.h"` (and leave everything else in this PR the same), `cpplint` does not raise any warnings.

image

If we want to stick to the intent of the style guide, I guess we could make (for example) `LightGBM/application.h` the first header and just add `//NOLINT`. That would be closer to what the style guide says, even if `cpplint` fails to pick it up. What do you think?

Comment (StrikerRUS) [reply src/application/application.cpp:14]: > Yes, if I move just `LightGBM/application.h` back to the top and leave everything else the same in this PR, I get this from `cpplint`

Oh, it's a pity! But thanks, this is exactly what I wanted to know.

> What do you think?

I think that adding `//NOLINT` in each file is very ugly "fix" and makes no sense. Quoting myself from https://github.com/microsoft/LightGBM/pull/2066
> IMHO, any order is OK in case it's the same across the whole project.

I suggest only document our own new style guide for includes. So that we will be able to use it as a reference for new files in the future. Just like I did it earlier:

> But due to [the bug](https://github.com/cpplint/cpplint/issues/43) only the following order doesn't produce errors:
```
dir2/foo2.h.
A blank line
Your project's .h files in include folder.
A blank line
C system files.
C++ system files.
A blank line
Other libraries' .h files.
Your project's .h files in src folder.
```

Comment (jameslamb) [reply src/application/application.cpp:14]: To be clear, do you mean I should push a commit adding this new standard somewhere? If so could you suggest where?

Comment (StrikerRUS) [reply src/application/application.cpp:14]: Ah, no! I mean, just post it here as a comment.
