### PR TITLE
ignore unknown parameters when loading from model file

### LINKED ISSUE #6082: lightgbm v3 model file not compatible with v4
## Description
Model file fit and output with v3.3.0 can not be loaded in with v4.0.0. 

Tested working using lightgbm v2.3.1 and v3.3.0.

Throws exception in v4.0.0. Tested in both Windows and Linux. 

In Linux (Ubuntu 20.04):
```Traceback (most recent call last):
  File "test.py", line 3, in <module>
    lgb.Booster(model_file='./test.txt')
  File "/opt/conda/lib/python3.8/site-packages/lightgbm/basic.py", line 3142, in __init__
    params = self._get_loaded_param()
  File "/opt/conda/lib/python3.8/site-packages/lightgbm/basic.py", line 3196, in _get_loaded_param
    _safe_call(_LIB.LGBM_BoosterGetLoadedParam(
  File "/opt/conda/lib/python3.8/site-packages/lightgbm/basic.py", line 237, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: unordered_map::at
```
Windows gives a slightly different error (attached screencap - could not copy text from test environment)
b283e05b-048d-482c-b654-1592c4bbf15c

## Reproducible example
Using attached [test.txt](https://github.com/microsoft/LightGBM/files/12545239/test.txt)

```
import lightgbm as lgb
lgb.Booster(model_file='./test.txt')
```

## Environment info
python 3.8.6 and python 3.11.3
LightGBM version: 3.3.0 and 4.0.0

Command(s) you used to install LightGBM

```shell
pip install lightgbm==3.3.0 
```
and
```shell
pip install lightgbm==4.0.0
```

### PR DESCRIPTION
**Pull request by jmoralez**
Issues a warning when a parameter type is not found when loading a booster from a model file instead of raising an error.

Fixes #6082

### CODE REVIEW

File: src/boosting/gbdt.h [hunk 1]
```diff
@@ -179,15 +179,20 @@ class GBDT : public GBDTBase {
       const auto pair = Common::Split(line.c_str(), ":");
       if (pair[1] == " ]")
         continue;
+      const auto param = pair[0].substr(1);
+      const auto value_str = pair[1].substr(1, pair[1].size() - 2);
+      auto iter = param_types.find(param);
+      if (iter == param_types.end()) {
+        Log::Warning("Type for param: '%s' not found. This doesn't affect inference.", param.c_str());
```
Comment (jameslamb) [inline src/boosting/gbdt.h:186]:
```suggestion
        Log::Warning("Ignoring unrecognized parameter '%s' found in model string.", param.c_str());
```

I understand that an error about types is the first place where an error is thrown in this situation... but from a user's perspective, I don't think that's important and in fact might be confusing.

I also don't think "This doesn't affect inference" is necessary. And it might become incorrect if parameters that do affect scoring trigger this warning in the future.

Would you consider this re-write? I think it's sufficient just to say "hey LightGBM found this parameter and skipped it".

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks very much for this! I think it'll really help people trying to use models from older versions with v4.x.

I'm supportive of this generally, just left one suggestion about the wording of the warning.

I think we should also get a review from @guolinke or @shiyu1994 before merging this.

File: tests/python_package_test/test_engine.py [hunk 2]
```diff
@@ -1487,8 +1487,18 @@ def test_parameters_are_loaded_from_model_file(tmp_path):
...
+    orig_bst = lgb.train(params, ds, num_boost_round=1, categorical_feature=[1, 2])
+    orig_bst.save_model(model_file)
+    with model_file.open('rt') as f:
+        model_contents = f.readlines()
+    params_start = model_contents.index('parameters:\n')
+    model_contents.insert(params_start + 1, '[max_conflict_rate: 0]\n')
+    with model_file.open('wt') as f:
+        f.writelines(model_contents)
     bst = lgb.Booster(model_file=model_file)
+    expected_msg = "[LightGBM] [Warning] Type for param: 'max_conflict_rate' not found. This doesn't affect inference."
```
Comment (jmoralez) [inline tests/python_package_test/test_engine.py:1499]:
```suggestion
    expected_msg = "[LightGBM] [Warning] Ignoring unrecognized parameter 'max_conflict_rate' found in model string."
```

**Review by jameslamb — APPROVED** [review]
Makes sense to me, thank you!

But let's please get a review from @guolinke or @shiyu1994 before merging.

**Review by guolinke — APPROVED** [review]
Thank you, LGTM
