### PR TITLE
Fix #2898: Clearer warning message for user (2^max_depth > num_leaves).

### LINKED ISSUE #2898: [doc] Warning message says "you didn't set num_leaves" even if I explicitly set num_leaves=31
## Environment info

Operating System: Ubuntu 18.04.3 LTS

CPU/GPU model: Not sure (running in AWS EC2)

C++/Python/R version: GCC 7.5/Python 3.7.5

LightGBM version or commit hash: 6b6709

## Error message

[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves

## Steps to reproduce

Fit any model with num_leaves = 31 and max_depth >= 5

At line 307 of src/io/config.cpp, the check for whether to show the warning can't tell whether num_leaves is 31 because that's the default or because 31 was explicitly passed. The text "you didn't set num_leaves" in the message is confusing if I did explicitly set num_leaves to 31.

### PR DESCRIPTION
**Pull request by AlbertoEAF**
Fix https://github.com/microsoft/LightGBM/issues/2898

Clearer warning message for user when `2^max_depth > num_leaves` happens.

### CODE REVIEW

File: src/io/config.cpp [hunk 1]
```diff
@@ -317,7 +317,9 @@ void Config::CheckParamConflict() {
     double full_num_leaves = std::pow(2, max_depth);
     if (full_num_leaves > num_leaves
         && num_leaves == kDefaultNumLeaves) {
-      Log::Warning("Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves");
+      Log::Warning("Accuracy may be bad since you didn't set num_leaves OR 2^max_depth > num_leaves."
```
Comment (StrikerRUS) [inline src/io/config.cpp:320]: Will it make more sense?
```suggestion
      Log::Warning("Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves."
```

File: src/io/config.cpp [hunk 2]
```diff
@@ -317,7 +317,9 @@ void Config::CheckParamConflict() {
...
+                   " (num_leaves=%d).",
```
Comment (StrikerRUS) [inline src/io/config.cpp:321]: To pass CI lint check.
```suggestion
                   " (num_leaves=%d).",
```

**Review by StrikerRUS — APPROVED** [review]
Thanks for making this warning clearer!

**Comment by AlbertoEAF** [comment]
Do you want to merge it @StrikerRUS ? :)
I have no permissions for that

**Comment by StrikerRUS** [comment]
@AlbertoEAF Yeah, thanks! I had to re-run all GitHub Actions due to #3469, because I'm not able to merge without all-green CIs.

**Comment by AlbertoEAF** [comment]
Thanks ;)
