### PR TITLE
Avoid segment fault in ResetConfig for GBDT in prediction (fix #3317)

### LINKED ISSUE #3317: segfault in LGBM_BoosterResetParameter()
Hello, in 2.3.2 and 3.0.0 the following segfaults in LGBM_BoosterResetParameter():

int out_num_iterations = 0;
BoosterHandle myBooster = 0;
int ret = LGBM_BoosterLoadModelFromString( model_str, &out_num_iterations, &myBooster );
if ( (!ret) && myBooster ) {
  ret = LGBM_BoosterResetParameter( myBooster, "num_threads=1" );
}

The crash occurs in gpdt.cpp
void GBDT::ResetConfig(const Config* config)
if (config_->forcedsplits_filename != new_config->forcedbins_filename) {
config_ is non-null but bogus, hence the segfault.

No crash in 2.2.3.

For 2.3.2/3.0.0, if I don't call LGBM_BoosterResetParameter() the booster works fine for inferencing.

Thank you for the help.

### PR DESCRIPTION
**Pull request by shiyu1994**
This PR is to fix #3317. When a booster is created from model file, its config_ member will be undefined. However, the ResetConfig method of GBDT is not aware of this. As @glarb pointed out.

### CODE REVIEW

**Review by guolinke — APPROVED** [review]

File: src/boosting/gbdt.cpp [hunk 1]
```diff
@@ -718,7 +719,7 @@ void GBDT::ResetConfig(const Config* config) {
   if (train_data_ != nullptr) {
     ResetBaggingConfig(new_config.get(), false);
   }
-  if (config_->forcedsplits_filename != new_config->forcedbins_filename) {
+  if (config_.get() != nullptr && config_->forcedsplits_filename != new_config->forcedbins_filename) {
```
Comment (btrotta) [inline src/boosting/gbdt.cpp:722]: @guolinke I think there might be a typo here, should it be `new_config->forcedsplits_filename` (instead of `new_config->forcedbins_filename`)?

Comment (guolinke) [reply src/boosting/gbdt.cpp:722]: @btrotta you are right, it is typo.

Comment (guolinke) [reply src/boosting/gbdt.cpp:722]: @btrotta can you help to create a PR?

Comment (btrotta) [reply src/boosting/gbdt.cpp:722]: @guolinke Done in #3392. 

@shiyu1994 Apologies, I just now realized you are the author of this PR, not guolinke. I should have mentioned you in my original comment.

**Comment by glarb** [comment]
Hi @shiyu1994, I think it would have been better for LGBM_BoosterResetParameter() to just create the config if it doesn't exist.  That way folks can set parameters once instead of for each predict (like we could before).  Please reconsider this fix, thanks.
