### PR TITLE
fix warnings

### LINKED ISSUE #3394: Compiler warnings with VS 2015
There are a lot of warnings produced by VS 2015:
```
C:\Users\ntitov\Downloads\LightGBM\build>cmake -A x64 ..
-- Building for: Visual Studio 14 2015
-- Selecting Windows SDK version 10.0.10586.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Performing Test MM_PREFETCH
-- Performing Test MM_PREFETCH - Failed
-- Performing Test MM_MALLOC
-- Performing Test MM_MALLOC - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/ntitov/Downloads/LightGBM/build

C:\Users\ntitov\Downloads\LightGBM\build>cmake --build . --target ALL_BUILD --config Release
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\User
s\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  metadata.cpp
C:\Users\ntitov\Downloads\LightGBM\src\io\dataset.cpp(380): warning C4800: 'signed char': forcing value to bool 'true'
or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter
(compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_li
ghtgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function '
  LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,const Li
  ghtGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source
   file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM
  ::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(310): warning C4100: 'max_bin': unreferenced formal parameter (
compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lig
htgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(362): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(359): note: while compiling class template member function 'L
  ightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,cons
  t LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling so
  urce file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM
  ::DenseBin<uint32_t,false>' being compiled
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
  c_api.cpp
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp(388): warning C4800: 'signed char': forcing
value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp(410): warning C4800: 'signed char': forcing
value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(203): warning C4800: 'signed char': f
orcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxpro
j]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(176): note: while compiling class t
  emplate member function 'void LightGBM::DataParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHistogra
  ms(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)'
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(171): note: see reference to functi
  on template instantiation 'void LightGBM::DataParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHistog
  rams(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)' being compiled
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(259): note: see reference to class
  template instantiation 'LightGBM::DataParallelTreeLearner<LightGBM::GPUTreeLearner>' being compiled
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(217): warning C4800: 'signed char': f
orcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxpro
j]
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(378): warning C4800: 'signed char':
 forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxp
roj]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(350): note: while compiling class
   template member function 'void LightGBM::VotingParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHist
  ograms(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)'
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(346): note: see reference to func
  tion template instantiation 'void LightGBM::VotingParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHi
  stograms(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)' being compiled
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(457): note: see reference to clas
  s template instantiation 'LightGBM::VotingParallelTreeLearner<LightGBM::GPUTreeLearner>' being compiled
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(394): warning C4800: 'signed char':
 forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxp
roj]
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\
ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\c_api.cpp(879): warning C4702: unreachable code [C:\Users\ntitov\Downloads\Light
GBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Us
ers\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lib_lightgbm.lib and object C:/Users/ntitov/Downloads/
  LightGBM/Release/lib_lightgbm.exp
  _lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lib_lightgbm.dll
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
C:\Users\ntitov\Downloads\LightGBM\src\io\dataset.cpp(380): warning C4800: 'signed char': forcing value to bool 'true'
or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\User
s\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  file_io.cpp
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter
(compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lig
htgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function '
  LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,const Li
  ghtGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source
   file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM
  ::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(310): warning C4100: 'max_bin': unreferenced formal parameter (
compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\ligh
tgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(362): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(359): note: while compiling class template member function 'L
  ightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,cons
  t LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling so
  urce file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM
  ::DenseBin<uint32_t,false>' being compiled
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(203): warning C4800: 'signed char': f
orcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj
]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(176): note: while compiling class t
  emplate member function 'void LightGBM::DataParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHistogra
  ms(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)'
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(171): note: see reference to functi
  on template instantiation 'void LightGBM::DataParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHistog
  rams(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)' being compiled
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(259): note: see reference to class
  template instantiation 'LightGBM::DataParallelTreeLearner<LightGBM::GPUTreeLearner>' being compiled
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp(217): warning C4800: 'signed char': f
orcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj
]
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp(388): warning C4800: 'signed char': forcing
value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp(410): warning C4800: 'signed char': forcing
value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\
ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(378): warning C4800: 'signed char':
 forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxpr
oj]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(350): note: while compiling class
   template member function 'void LightGBM::VotingParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHist
  ograms(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)'
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(346): note: see reference to func
  tion template instantiation 'void LightGBM::VotingParallelTreeLearner<LightGBM::GPUTreeLearner>::FindBestSplitsFromHi
  stograms(const std::vector<int8_t,std::allocator<_Ty>> &,bool,const LightGBM::Tree *)' being compiled
          with
          [
              _Ty=int8_t
          ]
  C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(457): note: see reference to clas
  s template instantiation 'LightGBM::VotingParallelTreeLearner<LightGBM::GPUTreeLearner>' being compiled
C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp(394): warning C4800: 'signed char':
 forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxpr
oj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Us
ers\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lightgbm.lib and object C:/Users/ntitov/Downloads/Ligh
  tGBM/Release/lightgbm.exp
  lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lightgbm.exe
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
```

To reproduce run [code from the guide](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#from-command-line):
```
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -A x64 ..
cmake --build . --target ALL_BUILD --config Release
```

### PR DESCRIPTION
**Pull request by guolinke**
to fix #3394

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke 
Looks like one warning about type casting still remains in this branch:
```
C:\Users\ntitov\Downloads\LightGBM\src\io\dataset.cpp(380): warning C4800: 'signed char': forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxpr
oj]
```
```
C:\Users\ntitov\Downloads\LightGBM\build>cmake --build . --target ALL_BUILD --config Release
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  metadata.cpp
C:\Users\ntitov\Downloads\LightGBM\src\io\dataset.cpp(380): warning C4800: 'signed char': forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxpr
oj]
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov
\Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32
  _t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32
  _t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(310): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\
Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(362): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(ui
  nt32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov
  \Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(ui
  nt32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov
  \Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(359): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_
  t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM::DenseBin<uint32_t,false>' being compiled
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
  c_api.cpp
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\c_api.cpp(879): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lib_lightgbm.lib and object C:/Users/ntitov/Downloads/LightGBM/Release/lib_lightgbm.exp
  _lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lib_lightgbm.dll
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
C:\Users\ntitov\Downloads\LightGBM\src\io\dataset.cpp(380): warning C4800: 'signed char': forcing value to bool 'true' or 'false' (performance warning) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxpro
j]
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  file_io.cpp
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov
\Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32
  _t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32
  _t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(310): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\
Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(362): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(ui
  nt32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov
  \Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(ui
  nt32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov
  \Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(359): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_
  t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM::DenseBin<uint32_t,false>' being compiled
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lightgbm.lib and object C:/Users/ntitov/Downloads/LightGBM/Release/lightgbm.exp
  lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lightgbm.exe
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
```

File: src/io/dataset.cpp [hunk 1]
```diff
@@ -377,7 +377,7 @@ void Dataset::Construct(std::vector<std::unique_ptr<BinMapper>>* bin_mappers,
       ++cur_fidx;
     }
     feature_groups_.emplace_back(std::unique_ptr<FeatureGroup>(new FeatureGroup(
-        cur_cnt_features, group_is_multi_val[i], &cur_bin_mappers, num_data_)));
+        cur_cnt_features, static_cast<bool>(group_is_multi_val[i]), &cur_bin_mappers, num_data_)));
```
Comment (guolinke) [inline src/io/dataset.cpp:380]:
```suggestion
        cur_cnt_features, group_is_multi_val[i], &cur_bin_mappers, num_data_)));
```

**Comment by StrikerRUS** [comment]
@guolinke More warnings about `int8` to `bool` conversion:
```
C:\Users\ntitov\Downloads\LightGBM\build>cmake --build . --target ALL_BUILD --config Release
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  json11.cpp
  metadata.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\gbdt_model_text.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\boosting.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\dataset_loader.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\application\application.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\gbdt.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\gbdt_prediction.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\dataset.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\metadata.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\D
ownloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t
  ,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Downloa
  ds\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t
  ,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Downloa
  ds\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,cons
  t uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(310): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Do
wnloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(362): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint
  32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint
  32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(359): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_t,
  const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM::DenseBin<uint32_t,false>' being compiled
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\parser.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  metric.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\tree.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\metric\dcg_calculator.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\metric\metric.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\objective\objective_function.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\data_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\feature_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
  c_api.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\serial_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\c_api.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\voting_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\c_api.cpp(879): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lib_lightgbm.lib and object C:/Users/ntitov/Downloads/LightGBM/Release/lib_lightgbm.exp
  _lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lib_lightgbm.dll
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\application\application.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\gbdt_prediction.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\boosting.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\dataset.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\gbdt_model_text.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\dataset_loader.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\boosting\gbdt.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  file_io.cpp
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\D
ownloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t
  ,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Downloa
  ds\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t
  ,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Downloa
  ds\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,cons
  t uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(310): warning C4100: 'max_bin': unreferenced formal parameter (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Do
wnloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(362): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint
  32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: see reference to function template instantiation 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint
  32_t,uint32_t,uint32_t,const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' being compiled (compiling source file C:\Users\ntitov\Dow
  nloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(359): note: while compiling class template member function 'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_t,
  const uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM::DenseBin<uint32_t,false>' being compiled
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\metadata.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\parser.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\metric\dcg_calculator.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\io\tree.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\metric\metric.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  feature_parallel_tree_learner.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\objective\objective_function.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\data_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  gpu_tree_learner.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\feature_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\serial_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
C:\Users\ntitov\Downloads\LightGBM\include\LightGBM/feature_group.h(32): warning C4800: 'int8_t': forcing value to bool 'true' or 'false' (performance warning) (compiling source file C:\Users\ntitov\Downloads\Li
ghtGBM\src\treelearner\voting_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lightgbm.lib and object C:/Users/ntitov/Downloads/LightGBM/Release/lightgbm.exp
  lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lightgbm.exe
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
```

File: src/treelearner/serial_tree_learner.cpp [hunk 2]
```diff
@@ -716,8 +716,11 @@ void SerialTreeLearner::RenewTreeOutput(Tree* tree, const ObjectiveFunction* obj
 
 void SerialTreeLearner::ComputeBestSplitForFeature(
     FeatureHistogram* histogram_array_, int feature_index, int real_fidx,
-    bool is_feature_used, int num_data, const LeafSplits* leaf_splits,
+    int8_t is_feature_used, int num_data, const LeafSplits* leaf_splits,
     SplitInfo* best_split, double parent_output) {
+  if (!is_feature_used) {
+    return;
+  }
```
Comment (guolinke) [inline src/treelearner/serial_tree_learner.cpp:723]:
```suggestion
```

**Comment by StrikerRUS** [comment]
@guolinke Thank you! I can confirm that warnings about `int -> bool` conversion have gone.

Could you please take a look at two new warnings (one about `double -> int` conversion is presented [in `master` branch CI](https://portal.azure.com/#@ufrf.onmicrosoft.com/resource/subscriptions/1cc8c543-e6f9-4dd8-97c9-22cfd4591d12/resourceGroups/trends2018/providers/Microsoft.Compute/virtualMachines/alfatrends/overview))? 

```
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
```

```
c:\users\ntitov\downloads\lightgbm\src\metric\multiclass_metric.hpp(339): warning C4244: 'argument': conversion from 'd
ouble' to 'unsigned __int64', possible loss of data (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\metri
c\metric.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
```

Full log:
```
C:\Users\ntitov\Downloads\LightGBM\build>cmake --build . --target ALL_BUILD --config Release
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\User
s\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  metadata.cpp
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter
(compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_li
ghtgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function '
  LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,const Li
  ghtGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source
   file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM
  ::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(311): warning C4100: 'max_bin': unreferenced formal parameter (
compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lig
htgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(363): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(361): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: while compiling class template member function 'L
  ightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,cons
  t LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling so
  urce file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM
  ::DenseBin<uint32_t,false>' being compiled
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  cuda_tree_learner.cpp
  data_parallel_tree_learner.cpp
c:\users\ntitov\downloads\lightgbm\src\metric\multiclass_metric.hpp(339): warning C4244: 'argument': conversion from 'd
ouble' to 'unsigned __int64', possible loss of data (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\metri
c\metric.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
  c_api.cpp
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\
ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\feature_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_le
  arner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\data_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learn
  er.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\serial_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\voting_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_lea
  rner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\c_api.cpp(891): warning C4702: unreachable code [C:\Users\ntitov\Downloads\Light
GBM\build\_lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Us
ers\ntitov\Downloads\LightGBM\build\_lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lib_lightgbm.lib and object C:/Users/ntitov/Downloads/
  LightGBM/Release/lib_lightgbm.exp
  _lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lib_lightgbm.dll
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
c:\users\ntitov\downloads\lightgbm\src\boosting\prediction_early_stop.cpp(88): warning C4702: unreachable code [C:\User
s\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  file_io.cpp
c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(355): warning C4100: 'max_bin': unreferenced formal parameter
(compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lig
htgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(407): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(405): note: see reference to function template instantiation
   'LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,const
  uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) c
  onst' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\sparse_bin.hpp(404): note: while compiling class template member function '
  LightGBM::data_size_t LightGBM::SparseBin<uint32_t>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,const Li
  ghtGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling source
   file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(629): note: see reference to class template instantiation 'LightGBM
  ::SparseBin<uint32_t>' being compiled
c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(311): warning C4100: 'max_bin': unreferenced formal parameter (
compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\ligh
tgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(363): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(361): note: see reference to function template instantiation
  'LightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategoricalInner<false>(uint32_t,uint32_t,uint32_t,co
  nst uint32_t *,int,const LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t
  *) const' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  c:\users\ntitov\downloads\lightgbm\src\io\dense_bin.hpp(360): note: while compiling class template member function 'L
  ightGBM::data_size_t LightGBM::DenseBin<uint32_t,false>::SplitCategorical(uint32_t,uint32_t,const uint32_t *,int,cons
  t LightGBM::data_size_t *,LightGBM::data_size_t,LightGBM::data_size_t *,LightGBM::data_size_t *) const' (compiling so
  urce file C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp)
  C:\Users\ntitov\Downloads\LightGBM\src\io\bin.cpp(625): note: see reference to class template instantiation 'LightGBM
  ::DenseBin<uint32_t,false>' being compiled
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
c:\users\ntitov\downloads\lightgbm\src\metric\multiclass_metric.hpp(339): warning C4244: 'argument': conversion from 'd
ouble' to 'unsigned __int64', possible loss of data (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\metri
c\metric.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  cuda_tree_learner.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
c:\users\ntitov\downloads\lightgbm\src\objective\objective_function.cpp(52): warning C4702: unreachable code [C:\Users\
ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\feature_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_le
  arner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\data_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learn
  er.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\data_parallel_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\serial_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\serial_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\voting_parallel_tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_lea
  rner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(175): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FindBestThresholdSequentially<true,false,true,true,true,true,true,
  false>(double,double,LightGBM::data_size_t,const LightGBM::FeatureConstraint *,double,LightGBM::SplitInfo *,int,doubl
  e)' being compiled (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(150): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL3<true,false,true,true,true>(void)' being compiled
   (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(134): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL2<true,false,true,true>(void)' being compiled (com
  piling source file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
  c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(118): note: see reference to function templa
  te instantiation 'void LightGBM::FeatureHistogram::FuncForNumricalL1<true,false>(void)' being compiled (compiling sou
  rce file C:\Users\ntitov\Downloads\LightGBM\src\treelearner\tree_learner.cpp)
c:\users\ntitov\downloads\lightgbm\src\treelearner\serial_tree_learner.cpp(233): warning C4702: unreachable code [C:\Us
ers\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]
     Creating library C:/Users/ntitov/Downloads/LightGBM/Release/lightgbm.lib and object C:/Users/ntitov/Downloads/Ligh
  tGBM/Release/lightgbm.exp
  lightgbm.vcxproj -> C:\Users\ntitov\Downloads\LightGBM\Release\lightgbm.exe
  Building Custom Rule C:/Users/ntitov/Downloads/LightGBM/CMakeLists.txt
```

**Comment by guolinke** [comment]
@StrikerRUS 
> c:\users\ntitov\downloads\lightgbm\src\treelearner\feature_histogram.hpp(873): warning C4189: 'constraint_update_necess
ary': local variable is initialized but not referenced (compiling source file C:\Users\ntitov\Downloads\LightGBM\src\tr
eelearner\tree_learner.cpp) [C:\Users\ntitov\Downloads\LightGBM\build\lightgbm.vcxproj]

This is also related to template, so cannot be fixed..

**Comment by StrikerRUS** [comment]
> This is also related to template, so cannot be fixed..

OK, got it, thanks!

**Review by StrikerRUS — APPROVED** [review]
@guolinke Thank you very much! I can confirm that only warnings about unreachable code and related to templates are left.
