### PR TITLE
Fix Integer Overflow #2357 

### LINKED ISSUE #2357: lgb.cv is constantly crashing in R
Unfortunately, my R Session is always aborted after a few seconds when running lgb.cv. I call lgb.cv several times since it's part of a scoring function I use to do Bayesian Optimization and hence find the optima hyper parameters. However, the error does seem to come from lightgbm. 

In RStudio, I get the following error:

[LightGBM] [Fatal] Check failed: cache_size >= 2 at /private/var/folders/6q/.../T/RtmpGrFClE/R.INSTALL10ba5306a71e/lightgbm/src/src/treelearner/feature_histogram.hpp, line 676.

If you have any idea what is this supposed to mean and how I could solve the issue, I would highly appreciate your help.

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
Fixes #2357

Please let me know if this is what you meant in your comment @guolinke 

Where should I add tests for this?

### CODE REVIEW

**Comment by chris-smith-zocdoc** [comment]
> Please use two-space indent, not 4.

Fixed. We could add an https://editorconfig.org/ file to automatically configure editor settings for people who use it. [Example](https://github.com/exercism/cpp/blob/master/.editorconfig)

**Comment by StrikerRUS** [comment]
How about simple explicit prohibition of large `max_depth` values in config as per https://github.com/microsoft/LightGBM/issues/2357#issuecomment-530402138?

`  // check = <=16`
https://github.com/microsoft/LightGBM/blob/b310fb417e4078cc30b153a5ef8f60c06d9ca9cf/include/LightGBM/config.h#L214-L216

**Comment by StrikerRUS** [comment]
> We could add an https://editorconfig.org/ file to automatically configure editor settings for people who use it. Example

Thanks a lot! Cool feature! I'm adding this to our **feature requests** (#2302) near the cpp lint test.

**Comment by chris-smith-zocdoc** [comment]
@guolinke @StrikerRUS Would you like anything else added to this pr? Should I add tests or update docs?

**Comment by guolinke** [comment]
ping @StrikerRUS for the test and doc.

**Comment by StrikerRUS** [comment]
@chris-smith-zocdoc @guolinke I think that new fatal error message is quite clear and no clarifications in docs are needed.

**Comment by chris-smith-zocdoc** [comment]
Thanks @StrikerRUS I think this is ready to merge then.

File: src/io/config.cpp [hunk 1]
```diff
@@ -307,12 +307,21 @@ void Config::CheckParamConflict() {
...
   if (max_depth > 0) {
-    int full_num_leaves = static_cast<int>(std::pow(2, max_depth));
+    double full_num_leaves = std::pow(2, max_depth);
     if (full_num_leaves > num_leaves
         && num_leaves == kDefaultNumLeaves) {
       Log::Warning("Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves");
     }
-    num_leaves = std::min(num_leaves, 2 << max_depth);
+    
+    const int MAX_LEAVES = 2 << 16;
```
Comment (StrikerRUS) [inline src/io/config.cpp]: Sorry, why do we use `16` here?

Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: Only because @guolinke suggested it https://github.com/microsoft/LightGBM/issues/2357#issuecomment-530402138

Comment (StrikerRUS) [reply src/io/config.cpp]: Ah, OK!
Why do we perform this check only in case of `if (max_depth > 0)`?

Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: No reason I guess, I put it there while I was adding the guard for the overflow. But now that you mention it, I don't see a reason why it couldn't be outside this block

Comment (StrikerRUS) [reply src/io/config.cpp]: I think this check should be performed independently of the `max_depth` value. In this case, the check and `kMaxNumLeaves` can be moved to `config.h` and simplify the code.

Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: I moved the constant to config.h and the check outside the max_depth check.

I'm not sure where I'd place the check inside `config.h` If you want, feel free to add commits to this pr directly

File: src/io/config.cpp [hunk 2]
```diff
@@ -306,13 +306,21 @@ void Config::CheckParamConflict() {
...
   if (max_depth > 0) {
-    int full_num_leaves = static_cast<int>(std::pow(2, max_depth));
+    double full_num_leaves = std::pow(2, max_depth);
     if (full_num_leaves > num_leaves
         && num_leaves == kDefaultNumLeaves) {
       Log::Warning("Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves");
     }
-    num_leaves = std::min(num_leaves, 2 << max_depth);
+
+    if (full_num_leaves < kMaxNumLeaves && full_num_leaves < num_leaves) {
```
Comment (guolinke) [inline src/io/config.cpp]: as `num_leaves <= kMaxNumLeaves`, do we need to check `full_num_leaves < kMaxNumLeaves` here ?

Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: Yes to prevent the overflow during the double to int cast

File: src/io/config.cpp (hunk 1 above)
Comment (StrikerRUS) [reply src/io/config.cpp]: > I'm not sure where I'd place the check inside config.h If you want, feel free to add commits to this pr directly

Unfortunately, I have no permission to commit in your branch.
https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I would like to replace `if (num_leaves > kMaxNumLeaves)` in `config.cpp` with `// check = <=131072` in `config.h` so that the check will be created automatically and users will be aware of the max value early during reading the docs.

Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: updated

File: src/io/config.cpp (hunk 2 above)
Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: Alternative I can make this `num_leaves  <= INT_MAX` if that makes this more clear

Comment (StrikerRUS) [reply src/io/config.cpp]: @chris-smith-zocdoc  I'm sorry, but I think that `full_num_leaves < kMaxNumLeaves` is excess too, because the second part `full_num_leaves < num_leaves` is more strict due to that we have a guarantee `num_leaves <= kMaxNumLeaves` (from `config.h`). Can you please elaborate a little bit more why it's needed?

Comment (chris-smith-zocdoc) [reply src/io/config.cpp]: Ah yes, you are correct. I'll make the change

**Comment by StrikerRUS** [comment]
@guolinke Can we merge this?
