### PR TITLE
[R-package] Use R standard routines to access numeric and integer array data in C++

### LINKED ISSUE #4216: (R) Functions that replace R headers are not compatible with all R versions
Migrated from here: https://github.com/microsoft/LightGBM/pull/4207

The R interface for LightGBM has replacements for R's internal headers which re-define the structs used by R's variables. These underlying structures behind R objects are however not constant between versions, and currently the LighGBM replacements will not work correctly with R 3.6 for windows and mac (which from the requirements is meant to be supported, and is tested in the CI pipelines in github here).

Example:
```r
library(lightgbm)
data(mtcars)
X <- as.matrix(mtcars[,-1])
y = mtcars[,1,drop=TRUE]
m = lightgbm(X, y, params=list(objective="regression", min_data=1))
pred_before = predict(m, X)
mode(X) = "double"
pred_after = predict(m, X)
```
```r
print(pred_before)
```
```
 [1] 20.68292 20.68292 21.85530 20.94345 19.18488 18.79409 16.31907 22.89741 21.85530 19.51054 18.59869 17.68684 18.27303
[14] 16.90526 13.77891 13.77891 16.57959 28.10799 26.80534 29.08497 21.00858 17.10065 16.90526 15.66774 19.51054 24.78625
[27] 23.93953 26.80534 17.29605 19.83620 16.77499 20.94345
```
```r
print(pred_after)
```
```
 [1] 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534
[14] 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534
[27] 26.80534 26.80534 26.80534 26.80534 26.80534 26.80534
```

(This was tested with R 3.6.3 and RTools35 on windows, but the problem will not be present if tested with R 4.0.4 in linux)

More concretely, what's failing there is the function `R_REAL_PTR(lightbm_struct)` (meant to obtain a pointer to the array of `double`s underneath an R matrix or vector), which does not output the same as the R C function `REAL(SEXP)`, returning instead a pointer to the address of some other array or struct. This not only causes incorrect results but can also lead to segmentation faults.

For now I think an easy solution would be to require R >= 4.0.0, but this is not a real solution as the structs can change at any time as the R headers are not meant to be replaced by libraries.

### PR DESCRIPTION
**Pull request by jameslamb**
Another step towards #3016.

Fixes #4216.

Changes in this PR:

* removes LightGBM-custom pointers to R data (`R_REAL_PTR()`, `R_INT_PTR()`) with the standard equivalents from `Rinternals.h` (`REAL()`, `INTEGER()`)
* converts arguments on the C++ side that are accessed that way from `LGBM_SE` to `SEXP`

### Description

R is a dynamically-typed language. You can run code like `x <- c(1, 2, 3)` without declaring that `x` is a numeric array, and R will just figure it out.

R makes this possible by storing data for an object in a structure called a `SEXPREC`. That structure will contain different data based on the R class (integer, character, function, etc.). Libraries can reference that data in C code using a type, `SEXP`, provided by `Rinternals.h`. Libraries can also get a pointer to a particular type of data within a `SEXPREC` using other functions provided by `Rinternals.h`, for example `REAL()` to get a pointer to its numeric data.

As described in #4216, the internal details of the `SEXPREC` struct can change between different versions of R. `SEXP` is the official R API into that struct, and by using it libraries can reliably stay compatible with multiple R versions.

This PR's changes fix a bug that currently exists when using `{lightgbm}` with R 3.6, and protects `{lightgbm}` from similar bugs in the future.

For more details on this, see https://cran.r-project.org/doc/manuals/r-release/R-ints.html#SEXPs.

### Notes for Reviewers

This PR does not depend on #4242 or #4247

### CODE REVIEW

File: R-package/tests/testthat/test_basic.R [hunk 1]
```diff
@@ -1247,6 +1247,38 @@ test_that("lgb.train() supports non-ASCII feature names", {
...
+    expect_equal(modelDT[, max(tree_index)], nrounds - 1L)
+    expect_gt(nrow(modelDT), nrounds * 3L)
+
+    # should have achieved expected performance
+    preds <- predict(bst, X)
+    mae <- mean(abs(y - preds))
+    expect_true(abs(mae - expected_mae) < TOLERANCE)
+  }
+})
+
```
Comment (jameslamb) [inline R-package/tests/testthat/test_basic.R:1281]: Thanks to @david-cortes for providing the write-up in https://github.com/microsoft/LightGBM/issues/4216, which included the reproducible example that inspired this unit test.

I tested this unit test tonight on my Mac, with R 3.6 and `{lightgbm}` 3.2.1 installed from CRAN, and confirmed that it failed in exactly the way described in #4216. So I'm confident that this test passing means the changes in this PR fix #4216.

**Review by StrikerRUS — APPROVED** [review]
Thank you very much for the iterative improvement!
