### PR TITLE
[fix] fix quantized training (fixes #5982) (fixes #5994)

### LINKED ISSUE #5982: Quantized training fails when a model is too complex
## Description

When a model is too complex and `use_quantized_grad` is `True`, training fails with this error:

```
[LightGBM] [Fatal] Check failed: (best_split_info.right_count) > (0) at /__w/1/s/lightgbm-python/src/treelearner/serial_tree_learner.cpp, line 855 .

Traceback (most recent call last):
  File "//main.py", line 16, in <module>
    lgb.train(params, lgb_train, num_boost_round=1000)
  File "/usr/local/lib/python3.10/site-packages/lightgbm/engine.py", line 266, in train
    booster.update(fobj=fobj)
  File "/usr/local/lib/python3.10/site-packages/lightgbm/basic.py", line 3557, in update
    _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
  File "/usr/local/lib/python3.10/site-packages/lightgbm/basic.py", line 237, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Check failed: (best_split_info.right_count) > (0) at /__w/1/s/lightgbm-python/src/treelearner/serial_tree_learner.cpp, line 855 .
```

## Reproducible example

```python
from sklearn.datasets import make_regression
X_train, y_train = make_regression(n_samples=1000, n_features=10, noise=1, random_state=42)

import lightgbm as lgb
lgb_train = lgb.Dataset(X_train, y_train)

params = {
    'device_type': 'cpu',
    'objective': 'mse',
    'num_leaves': 128,
    'use_quantized_grad': True,
    'verbose': -1,
    'seed': 0
}

lgb.train(params, lgb_train, num_boost_round=1000)
```

## Environment info

- python: 3.10

LightGBM version or commit hash: 4.0.0

Command(s) you used to install LightGBM

```shell
pip3 install lightgbm==4.0.0
```

I used this dockerfile

```Dockerfile
FROM python:3.10
RUN pip3 install \
    lightgbm==4.0.0 \
    scikit-learn==1.3.0
COPY main.py .
CMD python3 main.py
```
( `main.py` is the python script above)

## Additional Comments

When a model is not too complex (e.g. `num_boost_round=10`), training successfully finished even if `use_quantized_grad` is `True`.

### LINKED ISSUE #5994: Quantized Grad Randomly Fails `best_split_info.left_count` check
## Description

When using the new 'use_quantized_grad' in python, lightgbm will randomly fail, giving this error:

```
LightGBMError: Check failed: (best_split_info.right_count) > (0) at /__w/1/s/lightgbm-python/src/treelearner/serial_tree_learner.cpp, line 855 .
```

Even when locking in the random state, it will fail randomly. Run the below code multiple times and you'll see it occasionally passes but fails maybe 1/2 the time?

## Reproducible example

In google colab,

```
%pip install -U lightgbm
from lightgbm import LGBMRegressor
from sklearn.datasets import make_regression
X,y=make_regression()
while True:
    model = LGBMRegressor(use_quantized_grad=True, random_state=4, verbose=-1)
    model.fit(X,y)
    print('pass')
```
## Environment info

Google Colab
Python 3.10.6
LightGBM version or commit hash: 4.0.0

Command(s) you used to install LightGBM

```
%pip install -U lightgbm
```

### PR DESCRIPTION
**Pull request by shiyu1994**
This is to fix bugs in the CPU version of quantized training. I just missed some code when merging from https://github.com/shiyu1994/LightGBM/tree/cdd3bbddb02559a9589095220c84c55b48dffac4, which causes serious bugs.

Sorry for merging the quantized training PR too hasty without a careful check.

I've tested and this PR should fix #5982 and #5994, and probably #5868 (which needs to be confirmed by the results from test_dask.py in ci jobs).

### CODE REVIEW

**Review by guolinke — APPROVED** [review]

File: src/treelearner/leaf_splits.hpp [hunk 1]
```diff
@@ -53,6 +53,24 @@ class LeafSplits {
     weight_ = weight;
   }
 
+  /*!
+  * \brief Init split on current leaf on partial data. 
+  * \param leaf Index of current leaf
+  * \param data_partition current data partition
+  * \param sum_gradients
+  * \param sum_hessians
+  * \param sum_gradients_and_hessians
```
Comment (jameslamb) [inline src/treelearner/leaf_splits.hpp:62]:
```suggestion
  * \param sum_gradients_and_hessians
  * \param weight
```

Looks like this one was missed

**Review by jameslamb — APPROVED** [review]
Thanks! Just one small suggestion about a missing doc element.

**Comment by arya1030** [comment]
lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0)
Has the bug in the GPU version been fixed?
And are there any plans to fix it?
