### PR TITLE
avoid min_data and min_hessian are zeros at the same time

### LINKED ISSUE #3489: Lightgbm CPU learner error - lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0)
## How you are using LightGBM?

LightGBM component: 

## Environment info

Operating System:
Ubuntu 20.04
CPU/GPU model:
Threadripper 1920x
C++ compiler version:
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
CMake version:
3.16.3
Java version:
--
Python version:
3.8.5
R version:
--
Other:

LightGBM version or commit hash:
Version: 3.0.0

## Error message and / or logs

@guolinke Have just built it from the latest master branch, still fails. I'll try to separate a minimum reproducible example and create an issue then.

_Originally posted by @diditforlulz273 in https://github.com/microsoft/LightGBM/issues/2793#issuecomment-716483788_

[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /__w/1/s/python-package/compile/src/treelearner/serial_tree_learner.cpp, line 630 .

Traceback (most recent call last):
  File "/home/seva/PycharmProjects/ECOM_demand/lgbm_mre.py", line 41, in <module>
    model = lgb.train(lgb_params, train_dat, valid_sets=test_dat, verbose_eval=20)
  File "/home/seva/PycharmProjects/ECOM_demand/venv/lib/python3.8/site-packages/lightgbm/engine.py", line 252, in train
    booster.update(fobj=fobj)
  File "/home/seva/PycharmProjects/ECOM_demand/venv/lib/python3.8/site-packages/lightgbm/basic.py", line 2370, in update
    _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
  File "/home/seva/PycharmProjects/ECOM_demand/venv/lib/python3.8/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0) at /__w/1/s/python-package/compile/src/treelearner/serial_tree_learner.cpp, line 630 .

## Reproducible example(s)

Archive with code and pickled datasets, 4.5 kb total (lol really a MINIMAL reproducible example)

[https://drive.google.com/file/d/1y04Z_11Ce-sETRZPfwjBEBY-aSOMBcHK/view?usp=sharing](https://drive.google.com/file/d/1y04Z_11Ce-sETRZPfwjBEBY-aSOMBcHK/view?usp=sharing)
## Steps to reproduce

1.Run it on lgbm==3.0.0
2. ?????
3. NO PROFIT!
4. Run on lgbm==2.3.1
5.?????
6. PROFIT!

### PR DESCRIPTION
**Pull request by guolinke**
to fix #3489

### CODE REVIEW

File: src/io/config.cpp [hunk 1]
```diff
@@ -359,6 +359,12 @@ void Config::CheckParamConflict() {
   if (max_depth > 0 && monotone_penalty >= max_depth) {
     Log::Warning("Monotone penalty greater than tree depth. Monotone features won't be used.");
   }
+  if (min_data_in_leaf <= 0 and min_sum_hessian_in_leaf <= kEpsilon) {
```
Comment (guolinke) [inline src/io/config.cpp:362]:
```suggestion
  if (min_data_in_leaf <= 0 && min_sum_hessian_in_leaf <= kEpsilon) {
```

**Review by StrikerRUS — APPROVED** [review]
