### PR TITLE
openmp_wrapper.h stubs signature use __GOMP_NOTHROW

### LINKED ISSUE #3915: openmp/gcc compatibility problem with nothrow attribute -> lead compile error
gcc-9 has a different interface for some function, using the nothrow attribute. I wonder if the fake interface for lightgbm should use nothrow for gcc as well to be compatible. See the compile error below.

## How you are using LightGBM?

* C++ library

## Environment info

Operating System: Linux Ubunu 18.04
C++ compiler version: gcc 9
CMake version: >= 3.17
LightGBM version or commit hash: v3.0.0rc1

## Error message and / or logs

```
/usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h:112:12: error: declaration of 'int omp_get_num_threads() noexcept' has a different exception specifier
  112 | extern int omp_get_num_threads (void) __GOMP_NOTHROW;
In file included from /var/lib/jenkins/workspace/xxx//include/LightGBM/utils/common.h:9,
                 from /var/lib/jenkins/workspace/xxx//include/LightGBM/config.h:16,
                 from /var/lib/jenkins/workspace/xxx//include/LightGBM/dataset.h:8,
                 from /var/lib/jenkins/workspace/xxx//LGBMTree.cpp:7,
                 from /var/lib/jenkins/workspace/xxx/Unity/unity_27_cxx.cxx:5:
xxx/include/LightGBM/utils/openmp_wrapper.h:80:14: note: from previous declaration 'int omp_get_num_threads()'

      |            ^~~~~~~~~~~~~~~~~~~}
      |              ^~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by bsergean**
Fix #3915. OpenMP stubs do not use the noexcept attibute which is present in the gcc version of openmp, and which trigger compilation errors as seen below. dmlc-core uses the same technique and macro.

/usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h:114:12: error: declaration of ‘int omp_get_thread_num() noexcept’ has a different exception specifier
  114 | extern int omp_get_thread_num (void) __GOMP_NOTHROW;
      |            ^~~~~~~~~~~~~~~~~~
...
xxx/include/LightGBM/utils/openmp_wrapper.h:81:14: note: from previous declaration ‘int omp_get_thread_num()’
   81 |   inline int omp_get_thread_num() {return 0;}
      |              ^~~~~~~~~~~~~~~~~~

### CODE REVIEW

**Comment by bsergean** [comment]
The lint plan fails with cpplint not being found. Sounds like a setup issue, and that is ran on travis it seems. All the other checks look happy though.

File: include/LightGBM/utils/openmp_wrapper.h [hunk 1]
```diff
@@ -4,6 +4,21 @@
...
+#if defined(__clang__)
+#undef __GOMP_NOTHROW
+#define __GOMP_NOTHROW
+#elif defined(__cplusplus)
+#undef __GOMP_NOTHROW
+#define __GOMP_NOTHROW throw()
+#else
+#undef __GOMP_NOTHROW
+#define __GOMP_NOTHROW __attribute__((__nothrow__))
+#endif
```
Comment (StrikerRUS) [inline include/LightGBM/utils/openmp_wrapper.h:20]: I guess we don't need these `define`s in case of OpenMP is found and they should go under `#else` branch of `#ifdef _OPENMP` condition (line 67), shouldn't they?

Comment (bsergean) [reply include/LightGBM/utils/openmp_wrapper.h]: Make sense / I just moved it over there.

File: include/LightGBM/utils/openmp_wrapper.h [hunk 2]
```diff
@@ -66,6 +67,22 @@ class ThreadExceptionHelper {
 
 #else
 
+/*
+ * To be compatible with openmp, define a nothrow macro which is used by gcc
+ * openmp, but not by clang.
+ * See also https://github.com/dmlc/dmlc-core/blob/main/include/dmlc/omp.h#L14
```
Comment (jameslamb) [inline include/LightGBM/utils/openmp_wrapper.h:73]:
```suggestion
 * See also https://github.com/dmlc/dmlc-core/blob/3106c1cbdcc9fc9ef3a2c1d2196a7a6f6616c13d/include/dmlc/omp.h#L14
```

Could you please change this to a link to a specific commit? This will make the link understandable even if code gets moved / changed in `dmlc-core`.

**Review by jameslamb — DISMISSED** [review]

**Comment by StrikerRUS** [comment]
cpplint is working now and yields the following errror:
```
include/LightGBM/utils/openmp_wrapper.h:96:  Using C-style cast.  Use static_cast<int>(...) instead  [readability/casting] [4]
```
@bsergean Could you please fix it?

**Comment by bsergean** [comment]
```
include/LightGBM/utils/openmp_wrapper.h:96:  Using C-style cast.  Use static_cast<int>(...) instead  [readability/casting] [4]
```

On line [96](https://github.com/microsoft/LightGBM/blob/d1eba966bcd2be06b21b998339da83e116052fad/include/LightGBM/utils/openmp_wrapper.h#L96) there isn't any cast that I can see.

Do you know what's going on ? Is it in the inlined code that a cast exists ?

**Comment by StrikerRUS** [comment]
@bsergean 

> Do you know what's going on ?

Sorry, I'm not a cpp coder. If you are sure this error is false positive, feel free to mark that line as `// NOLINT` or `// NOLINTNEXTLINE`.

**Comment by StrikerRUS** [comment]
To cpp reviewers.
As we do not test [threadless version of LightGBM](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-threadless-version-not-recommended) on our CIs, I've run some tasks manually with `-DUSE_OPENMP=OFF` flag.
All builds with `gcc 10.2.0` on macOS, `gcc 4.8.4` on Linux, `Clang 10.0.0` on Linux, `AppleClang 9.1.0.9020039` on macOS were passed.

**Review by guolinke — APPROVED** [review]
Thank you!

**Comment by StrikerRUS** [comment]
@jameslamb Your review comment was addressed I believe, but your [review](https://github.com/microsoft/LightGBM/pull/3923#pullrequestreview-586090218) blocks merging. Could you please unblock?

**Comment by jameslamb** [comment]
sorry, didn't realize my review was blocking
