### PR TITLE
[c++] Fixed Predictor lifecycle and trees initialization in Contrib mode

### LINKED ISSUE #5482: Is predict(..., pred_contrib=True) thread safe?
## Description

I'm using the model behind a gRCP prediction service. The service predicts one example at a time.

I can reproduce the bug locally like

```python
data = [df.loc[:1][model.feature_name()]] * 1_000

def _predict(df_one_row):
    return model.predict(df_one_row, pred_contrib=True)

with ThreadPoolExecutor(max_workers=32) as exc:
    exc.map(_predict, data)
```

The error is like

```
free(): invalid next size (normal)
```
or 
```
double free or corruption (!prev)
```
or 
```
malloc(): corrupted top size
```

depending on different runs.

* If I set `max_workers=1`, the error seems to go away.
* If I remove `pred_contrib=True`, the error seems to go away, so it looks `predict` alone is thread-safe, consistent with https://github.com/microsoft/LightGBM/issues/666

## Reproducible example

I can produce some diff error, but also related to threading using the following code:

```python
from concurrent.futures import ThreadPoolExecutor

import sklearn.datasets
import lightgbm

df = (
    sklearn.datasets.load_iris(as_frame=True)["frame"]
    .sample(99, random_state=123)
    .rename(
        columns={
            "sepal length (cm)": "sepal_length",
            "sepal width (cm)": "sepal_width",
            "petal length (cm)": "petal_length",
            "petal width (cm)": "petal_width",
        }
    )
    .assign(sepal_length_cat=lambda df: (df.sepal_length > 1).astype(str).astype('category'))
    .reset_index(drop=True)
)

X, y = df.drop(columns="target"), df["target"]

regressor = lightgbm.LGBMRegressor(n_estimators=100, max_depth=7, objective="mse").fit(
    X, y
)

regressor.fit(X, y)

model = regressor.booster_

print(f'{df.dtypes=:}')

data = [df.loc[:1][model.feature_name()]] * 10_000


def _predict(df_one_row):
    return model.predict(df_one_row, pred_contrib=True)


with ThreadPoolExecutor(max_workers=32) as exc:
    exc.map(_predict, data)
```

The error is like

```
corrupted size vs. prev_size
corrupted size vs. prev_size
```
or 
```
python3: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
```

## Environment info

LightGBM version or commit hash:

lightgbm==3.3.2

Command(s) you used to install LightGBM

I'm using lightgbm inside a monorepo with bazel, but I think under the hood it's equivalent to `python -m pip install lightgbm`

### PR DESCRIPTION
**Pull request by AndreyOrb**
1) Fixed Predictor lifecycle
2) Fixed Boosting trees initialization

Fixed #5482

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for this! Will defer to other reviewers with more C++ experience but one question... is it possible to test that correctness of this by adding test cases in https://github.com/microsoft/LightGBM/tree/master/tests/cpp_tests?

There are tests on prediction there, but I specifically mean testing that this previously-not-thread-safe behavior remains thread-safe.

That'd reduce the risk of issues be re-introduced in future refactorings.

**Comment by jameslamb** [comment]
Ah interesting. Looking at that error, I suspect the issue is the working directory you're running from. That test has hard-coded relative paths from the root of the repo, so the `testlightgbm` binary only works if invoked from the root of the repo.

Here's how we run the tests in continuous integration:

https://github.com/microsoft/LightGBM/blob/e0c34e7b2f68793bbf46854b85fd750be134446d/.ci/test.sh#L61-L63

> Where should I add the test? In test_single_row.cpp ?

Yep that seems like a good place, thanks!

**Comment by AndreyOrb** [comment]
You are right. Changing the working directory has helped.
image

Baseline tests have passed:
image

I have updated the tests to check Contrib prediction type.
Here I can see that several threads enter the "danger" code area:
image

The new test before the fix manages to crash the test:
image
image

I used 100 iterations to ensure I hit the raise condition:
image

But then, the test is becoming slow:
image

For production, I reduced the number to 5:
image

**Comment by AndreyOrb** [comment]
Is there anything else I should do to push the PR?

**Review by jameslamb — COMMENTED** [review]
I have no other comments. Hoping @shiyu1994 or @guolinke can review this when they have time.

**Comment by AndreyOrb** [comment]
@shiyu1994, @guolinke Could you review the PR? 
I'm afraid I will not be able to fix the PR later, if anything pops up.

**Review by guolinke — APPROVED** [review]
Thank you!

**Review by jameslamb — APPROVED** [review]

File: tests/cpp_tests/test_single_row.cpp [hunk 1]
```diff
@@ -12,132 +12,176 @@
...
-
-    for (int i = 0; i < 51; i++) {
-        int is_finished;
-        result = LGBM_BoosterUpdateOneIter(
-            booster_handle,
-            &is_finished);
-        EXPECT_EQ(0, result) << "LGBM_BoosterUpdateOneIter result code: " << result;
+void test_predict_type(int predict_type, int num_predicts) {
+  // Load some test data
+  int result;
```
Comment (StrikerRUS) [inline tests/cpp_tests/test_single_row.cpp:17]: @AndreyOrb Could you please revert "4 spaces -> 2 spaces" indent change to make the diff for this file look good?

Comment (AndreyOrb) [reply tests/cpp_tests/test_single_row.cpp]: Done.

**Review by StrikerRUS — APPROVED** [review]
LGTM, thanks a lot for your PR!
