### PR TITLE
[R-package] skip integer categorical feature check when building dataset subset (fixes #6412)

### LINKED ISSUE #6412: [R-package] lgb.cv() fails with categorical features
## Description
Executing a cross-validation with `lgb.cv()` fails when the data contains categorical features.

## Reproducible example
I'm using the example in the code demo [categorical_features_rules](https://github.com/microsoft/LightGBM/blob/master/R-package/demo/categorical_features_rules.R):
```shell
demo("categorical_features_rules", "lightgbm")  # executes the example
``` 
In that example, a `lgb.Booster` is trained with 
```shell
model <- lgb.train(
    params = params
    , data = dtrain
    , nrounds = 100L
    , valids = list(train = dtrain, valid = dtest)
)
```
after the training and test data had been previously created as
```shell
dtrain <- lgb.Dataset(
    data = my_data_train
    , label = bank_train$y
    , categorical_feature = c(2L, 3L, 4L, 5L, 7L, 8L, 9L, 11L, 16L)
)
dtest <- lgb.Dataset.create.valid(
    dtrain
    , data = my_data_test
    , label = bank_test$y
)
```
Works perfectly so far. Now, if I want to cross-validate using the training data set, by doing
```shell
lgb.cv(
  params = params
  , data = dtrain
  , nrounds = 100L)
```
I'm getting an error
```shell
Error in if (data_is_not_filename && max(private$categorical_feature) >  : 
  missing value where TRUE/FALSE needed
```
Specifying the `categorical_feature` argument again in `lgb.cv()` does not help.

The error seems to be related to categorical features. When I'm, running a similar analysis without them, `lgb.cv()` works fine:
```shell
dtrain_nocat <- lgb.Dataset(
  data = my_data_train
  , label = bank_train$y
  # no categorical_feature here!
)
lgb.cv(
  params = params
  , data = dtrain_nocat
  , nrounds = 100L)
```

## Environment info
```
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.utf8  LC_CTYPE=German_Switzerland.utf8    LC_MONETARY=German_Switzerland.utf8
[4] LC_NUMERIC=C                        LC_TIME=German_Switzerland.utf8    

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.8 lightgbm_4.3.0   

loaded via a namespace (and not attached):
[1] compiler_4.3.1    R6_2.5.1          Matrix_1.6-4      parallel_4.3.1    tools_4.3.1       rstudioapi_0.15.0
[7] grid_4.3.1        jsonlite_1.8.5    lattice_0.21-8   
````

### PR DESCRIPTION
**Pull request by jmoralez**
Fixes #6412 

When creating the folds for cv we slice the dataset, which just calls the constructor passing the same arguments and the `used_indices`. If `free_raw_data = TRUE` then by the time this constructor is called there isn't raw data anymore, however, we also don't need to check if the categorical feature indices are out of bounds because this has already been checked when constructing the original dataset (and the categorical features can't be changed once the dataset has been constructed).

This adds a check to see if we're building a subset and skips the validation. We can rely on that condition because it's checked afterwards
https://github.com/microsoft/LightGBM/blob/6e78e697f8e27d4bbf493a0ebd9134c3254a2ecd/R-package/R/lgb.Dataset.R#L202-L212

### CODE REVIEW

File: R-package/tests/testthat/test_basic.R [hunk 1]
```diff
@@ -3652,6 +3652,28 @@ test_that("lgb.cv() only prints eval metrics when expected to", {
   )
 })
 
+test_that("lgb.cv() works with an already constructed dataset with integer categoricals", {
```
Comment (jameslamb) [inline R-package/tests/testthat/test_basic.R:3655]: Since this is testing code in `lgb.Dataset`, would you consider moving it into `test_dataset.R`? I think it's similar to this one:

https://github.com/microsoft/LightGBM/blob/6e78e697f8e27d4bbf493a0ebd9134c3254a2ecd/R-package/tests/testthat/test_dataset.R#L407

File: R-package/tests/testthat/test_basic.R [hunk 2]
```diff
@@ -3652,6 +3652,28 @@ test_that("lgb.cv() only prints eval metrics when expected to", {
...
+    , params = list(num_threads = .LGB_MAX_THREADS)
+  )
+  dtrain$construct()
+  params <- list(
+    objective = "regression"
+    , num_leaves = 2L
+    , verbose = .LGB_VERBOSITY
+    , num_threads = .LGB_MAX_THREADS
+  )
+  lgb.cv(params = params, data = dtrain, nrounds = 1L)
```
Comment (jameslamb) [inline R-package/tests/testthat/test_basic.R:3674]: could you add an assertion here that something happened? Just to give us a bit more confidence that this behavior didn't result in something like an early return with no training.

For example, maybe some of these checks that the returned objective contains metrics computed on the validation sets created by `lgb.cv()`:

https://github.com/microsoft/LightGBM/blob/6e78e697f8e27d4bbf493a0ebd9134c3254a2ecd/R-package/tests/testthat/test_basic.R#L469-L492

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks! The fix looks great. I really appreciate the thorough description... makes perfect sense to me.

I just left some comments about testing.

Could you please also add one more test in `test_dataset.R` checking that the expected error message *is actually raised* under one of the conditions in that `if` statement being modified here? 

Similar to this one:

https://github.com/microsoft/LightGBM/blob/6e78e697f8e27d4bbf493a0ebd9134c3254a2ecd/R-package/tests/testthat/test_dataset.R#L620-L622

**Comment by jameslamb** [comment]
@jmoralez if you have time in the next week or so, could you update this to latest `master` and consider the review comments? I'd like to get this into v4.4.0 if we can.

**Comment by jmoralez** [comment]
The R-package 3.6 jobs are failing with this message ([sample logs](https://github.com/microsoft/LightGBM/actions/runs/9453617732/job/26039389503?pr=6442#step:10:3065)):

>  ERROR: dependency ‘evaluate’ is not available for package ‘knitr’
removing ‘/github/home/Rlib/knitr’
ERROR: dependency ‘evaluate’ is not available for package ‘testthat’
removing ‘/github/home/Rlib/testthat’

It seems [evaluate](https://cran.rstudio.com/web/packages/evaluate/index.html) 0.24.0 was published today which requires R >= 4.0.0

**Comment by jmoralez** [comment]
@jameslamb should I add something like `Rscript --vanilla -e "install.packages('https://cran.r-project.org/src/contrib/Archive/evaluate/evaluate_0.23.tar.gz', repos = NULL, lib = '${R_LIB_PATH}')` after [this](https://github.com/microsoft/LightGBM/blob/44014015536574743b5d0eb7b4791258268090b7/.ci/test_r_package.sh#L112)?

**Comment by mayer79** [comment]
> The R-package 3.6 jobs are failing with this message ([sample logs](https://github.com/microsoft/LightGBM/actions/runs/9453617732/job/26039389503?pr=6442#step:10:3065)):
> 
> > ERROR: dependency ‘evaluate’ is not available for package ‘knitr’
> > removing ‘/github/home/Rlib/knitr’
> > ERROR: dependency ‘evaluate’ is not available for package ‘testthat’
> > removing ‘/github/home/Rlib/testthat’
> 
> It seems [evaluate](https://cran.rstudio.com/web/packages/evaluate/index.html) 0.24.0 was published today which requires R >= 4.0.0

Minor remark to @jameslamb: dropping version 3 should not be a too big deal. The main branch of XGBoost even requires R >= 4.3.0.

**Comment by jameslamb** [comment]
Thanks for investigating it @jmoralez .

I think we should do what we can to preserve R 3.x support for this release (including manually installing more packages in CI if necessary).

The first release of R 4.x was only 4 years ago (https://cran.r-project.org/bin/windows/base/old/).

By comparison, the oldest version of Python LightGBM supports (3.7) was first released about 6 years ago. (https://devguide.python.org/versions/)

Could you try to get this PR working with R 3.6 if it's not too much effort, and write up an `[RFC]` issue (similar to #6436) where we can discuss and track the work dropping R 4 in the **next** release? I totally support dropping it in the next release, and including a note in v4.4.0's release notes like "this will be the last release to support R 3.x".

I do hear what you're saying @mayer79 , but I I've worked in organizations where a major-version upgrade of a language happens on a slightly longer timescale than 4 years. If the cost of keeping R 3.x support for the v4.4.0 release is "have to install a few more libraries manually in CI", I think it's worth it to do that.

**Comment by jmoralez** [comment]
It seems there's also a failure in the MSVC job when building the vignettes ([this PR](https://github.com/microsoft/LightGBM/actions/runs/9455308995/job/26046235981?pr=6442#step:10:80), [#6467](https://github.com/microsoft/LightGBM/actions/runs/9434311017/job/26003604262#step:10:80)). Not sure how to debug that since the full error is just:

> creating vignettes ... ERROR
 --- re-building 'basic_walkthrough.Rmd' using knitr

**Comment by jameslamb** [comment]
I can look into the MSVC issues right now. I'll do that over in a separate PR (#6476), in case you want to use this PR to debug ... but if I find a fix, I'll push it here.

**Comment by jameslamb** [comment]
👀 I just noticed that all the Windows R-package jobs passed 11 hours ago, on this PR that has nothing to do with the R package:

* PR: #6478
* build: https://github.com/microsoft/LightGBM/actions/runs/9485380089/job/26153370408

Maybe we're gonna get lucky and the failing MSVC job here was just something temporary with GitHub Actions? I just restarted the failing job here, let's see.

**Review by jameslamb — APPROVED** [review]
changes look great, and thanks for the tests!

**Comment by jameslamb** [comment]
The job passed!

Ok I'm treating this as just something temporary, possibly fixed by the latest updates to the `windows-2022` VM image (https://github.com/actions/runner-images/pull/10041).
