### PR TITLE
fix predict with header

### LINKED ISSUE #2642: A model outputs sometimes different prediction when using test data exchanging columns or dropping ignore columns
A model outputs sometimes different prediction using test data exchanging columns.
```
$ head tmp.tsv 
label	qid	f1	f2	f3	f4
0	100	0.5866203427784302	0.2973507383790617	0.5866942587610317	0.16317055701055172
0	100	0.26027277989715025	0.7572217432377987	0.22977386280621914	0.07149896150401003
0	100	0.08945421366371675	0.820441457578729	0.10048853760794918	0.6576665693793531
1	100	0.15510159660984812	0.05900447430614619	0.6212568816292927	0.6371041964329608
2	100	0.47297679112666824	0.5973428460248122	0.9955008802207073	0.8817819551787094
0	101	0.6405971621282096	0.8583725832329346	0.30144986682652675	0.573930442847047
0	101	0.8846986854185849	0.43882154349407665	0.11089276033128104	0.643854668005951
0	101	0.966910127489074	0.1275841882344404	0.04534562238649187	0.41193587862889114
1	101	0.852670501885811	0.06666994507694146	0.400796524340746	0.7602185563131136

$ lightgbm task=train objective=lambdarank output_model=lgbm_model.txt data=tmp.tsv header=true label=name:label group=name:qid
...
[LightGBM] [Info] 0.043130 seconds elapsed, finished iteration 98
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] 0.043553 seconds elapsed, finished iteration 99
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] 0.043918 seconds elapsed, finished iteration 100
[LightGBM] [Info] Finished training

$ lightgbm task=predict input_model=lgbm_model.txt data=tmp.tsv header=true output_result=pred_tmp.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

$ head pred_tmp.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743

# exchanging f1 and f4
$ head shuffle1.tsv 
label	qid	f4	f2	f3	f1
0	100	0.16317055701055172	0.2973507383790617	0.5866942587610317	0.5866203427784302
0	100	0.07149896150401003	0.7572217432377987	0.22977386280621914	0.26027277989715025
0	100	0.6576665693793531	0.820441457578729	0.10048853760794918	0.08945421366371675
1	100	0.6371041964329608	0.05900447430614619	0.6212568816292927	0.15510159660984812
2	100	0.8817819551787094	0.5973428460248122	0.9955008802207073	0.47297679112666824
0	101	0.573930442847047	0.8583725832329346	0.30144986682652675	0.6405971621282096
0	101	0.643854668005951	0.43882154349407665	0.11089276033128104	0.8846986854185849
0	101	0.41193587862889114	0.1275841882344404	0.04534562238649187	0.966910127489074
1	101	0.7602185563131136	0.06666994507694146	0.400796524340746	0.852670501885811

$ lightgbm task=predict input_model=lgbm_model.txt data=shuffle1.tsv header=true output_result=pred_shuffle1.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

# same prediction
$ head pred_shuffle1.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743

# exchanging label and f2
$ head shuffle2.tsv 
f2	qid	f1	label	f3	f4
0.2973507383790617	100	0.5866203427784302	0	0.5866942587610317	0.16317055701055172
0.7572217432377987	100	0.26027277989715025	0	0.22977386280621914	0.07149896150401003
0.820441457578729	100	0.08945421366371675	0	0.10048853760794918	0.6576665693793531
0.05900447430614619	100	0.15510159660984812	1	0.6212568816292927	0.6371041964329608
0.5973428460248122	100	0.47297679112666824	2	0.9955008802207073	0.8817819551787094
0.8583725832329346	101	0.6405971621282096	0	0.30144986682652675	0.573930442847047
0.43882154349407665	101	0.8846986854185849	0	0.11089276033128104	0.643854668005951
0.1275841882344404	101	0.966910127489074	0	0.04534562238649187	0.41193587862889114
0.06666994507694146	101	0.852670501885811	1	0.400796524340746	0.7602185563131136

$ lightgbm task=predict input_model=lgbm_model.txt data=shuffle2.tsv header=true output_result=pred_shuffle2.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

# different prediction
$ head pred_shuffle2.txt 
-0.67235347824716607
-0.16244632609872744
-0.66399247109482551
-0.86365502010495199
0.28472810764995404
-1.9938820152862542
-0.6741335210297531
-0.81249028101368681
0.58212018516630726
-0.10961843784772886

# exchanging label and qid
$ head shuffle3.tsv 
qid	label	f1	f2	f3	f4
100	0	0.5866203427784302	0.2973507383790617	0.5866942587610317	0.16317055701055172
100	0	0.26027277989715025	0.7572217432377987	0.22977386280621914	0.07149896150401003
100	0	0.08945421366371675	0.820441457578729	0.10048853760794918	0.6576665693793531
100	1	0.15510159660984812	0.05900447430614619	0.6212568816292927	0.6371041964329608
100	2	0.47297679112666824	0.5973428460248122	0.9955008802207073	0.8817819551787094
101	0	0.6405971621282096	0.8583725832329346	0.30144986682652675	0.573930442847047
101	0	0.8846986854185849	0.43882154349407665	0.11089276033128104	0.643854668005951
101	0	0.966910127489074	0.1275841882344404	0.04534562238649187	0.41193587862889114
101	1	0.852670501885811	0.06666994507694146	0.400796524340746	0.7602185563131136

$ lightgbm task=predict input_model=lgbm_model.txt data=shuffle3.tsv header=true output_result=pred_shuffle3.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

# same prediction
$ head pred_shuffle3.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743
```

And a model outputs different prediction using test data without a ignore column.
```
$ lightgbm task=train objective=lambdarank data=tmp.tsv output_model=lgbm_ignore_model.txt header=true label=name:label group=name:qid ignore_column=name:f4
...
[LightGBM] [Info] 0.042189 seconds elapsed, finished iteration 98
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] 0.042654 seconds elapsed, finished iteration 99
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] 0.043148 seconds elapsed, finished iteration 100
[LightGBM] [Info] Finished training

$ lightgbm task=predict input_model=lgbm_ignore_model.txt data=tmp.tsv header=true output_result=pred_tmp_ignore.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

$ head pred_tmp_ignore.txt 
-0.43058259683609235
-0.098525361939025474
-0.2048474171242694
0.026815875041871856
0.94411773547211675
-0.89330324800246408
-1.3645662587572376
-0.5720641564103417
-0.46146592181818258
0.069007612700339171

# dropping f4
$ head drop_column.tsv 
label	qid	f1	f2	f3
0	100	0.5866203427784302	0.2973507383790617	0.5866942587610317
0	100	0.26027277989715025	0.7572217432377987	0.22977386280621914
0	100	0.08945421366371675	0.820441457578729	0.10048853760794918
1	100	0.15510159660984812	0.05900447430614619	0.6212568816292927
2	100	0.47297679112666824	0.5973428460248122	0.9955008802207073
0	101	0.6405971621282096	0.8583725832329346	0.30144986682652675
0	101	0.8846986854185849	0.43882154349407665	0.11089276033128104
0	101	0.966910127489074	0.1275841882344404	0.04534562238649187
1	101	0.852670501885811	0.06666994507694146	0.400796524340746

$ lightgbm task=predict input_model=lgbm_ignore_model.txt data=drop_column.tsv header=true output_result=pred_drop_column_ignore.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Data file drop_column.tsv doesn't contain a label column
[LightGBM] [Info] Finished prediction

# different prediction
$ head pred_drop_column_ignore.txt
-1.4770125016867441
0.21396952207603573
0.21396952207603573
-0.5720641564103417
-1.1489058928142166
-0.27021277394555143
0.56878758830786735
-0.26299255762334944
-0.26299255762334944
0.21396952207603573

# dropping f4. adding g1 and g2
$ head add_column.tsv 
label	qid	f1	f2	f3	g1	g2
0	100	0.5866203427784302	0.2973507383790617	0.5866942587610317	0.7831823147487917	0.3287357659260194
0	100	0.26027277989715025	0.7572217432377987	0.22977386280621914	0.9560662865775058	0.46951422359645945
0	100	0.08945421366371675	0.820441457578729	0.10048853760794918	0.966815436870278	0.979153732212909
1	100	0.15510159660984812	0.05900447430614619	0.6212568816292927	0.07619010464390419	0.8141398435123113
2	100	0.47297679112666824	0.5973428460248122	0.9955008802207073	0.12602243295848203	0.18799052034065
0	101	0.6405971621282096	0.8583725832329346	0.30144986682652675	0.027937341082152622	0.04113516120246541
0	101	0.8846986854185849	0.43882154349407665	0.11089276033128104	0.6596090641808335	0.9556473570660647
0	101	0.966910127489074	0.1275841882344404	0.04534562238649187	0.5361890928061973	0.7244894729768796
1	101	0.852670501885811	0.06666994507694146	0.400796524340746	0.8815337987349032	0.40199863028198923

$ lightgbm task=predict input_model=lgbm_ignore_model.txt data=add_column.tsv header=true output_result=pred_add_column_ignore.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

# same prediction
$ head pred_add_column_ignore.txt 
-0.43058259683609235
-0.098525361939025474
-0.2048474171242694
0.026815875041871856
0.94411773547211675
-0.89330324800246408
-1.3645662587572376
-0.5720641564103417
-0.46146592181818258
0.069007612700339171
```
I'd like to know why. Does LightGBM predict correctly?

### PR DESCRIPTION
**Pull request by guolinke**
to fix #2642

### CODE REVIEW

**Comment by guolinke** [comment]
@araman0 can you try this fix?

File: src/application/predictor.hpp [hunk 1]
```diff
@@ -135,31 +135,38 @@ class Predictor {
...
       std::vector<std::string> header_words = Common::Split(first_line.c_str(), "\t,");
-      header_words.erase(header_words.begin() + boosting_->LabelIdx());
+      std::unordered_map<std::string, int> header_mapper;
       for (int i = 0; i < static_cast<int>(header_words.size()); ++i) {
-        for (int j = 0; j < static_cast<int>(boosting_->FeatureNames().size()); ++j) {
-          if (header_words[i] == boosting_->FeatureNames()[j]) {
-            feature_names_map_[i] = j;
-            break;
-          }
+        if (header_mapper.count(header_words[i]) > 0) {
```
Comment (chivee) [inline src/application/predictor.hpp]: never be used?

File: src/io/parser.cpp [hunk 2]
```diff
@@ -201,18 +201,19 @@ Parser* Parser::CreateParser(const char* filename, bool header, int num_features
...
+    ret.reset(new TSVParser(output_label_index, num_col));
   } else if (type == DataType::CSV) {
-    label_idx = GetLabelIdxForCSV(lines[0], num_features, label_idx);
-    ret.reset(new CSVParser(label_idx, num_col));
+    output_label_index = GetLabelIdxForCSV(lines[0], num_features, label_idx);
+    ret.reset(new CSVParser(output_label_index, num_col));
   }
 
-  if (label_idx < 0) {
+  if (output_label_index < 0 && label_idx >= 0) {
```
Comment (araman0) [inline src/io/parser.cpp]: @guolinke 
It doesn't output "Data file drop_label.tsv doesn't contain a label column."
```
$ head tmp.tsv 
label	qid	f1	f2	f3	f4
0	100	0.13835814976295646	0.4402769613464669	0.946869449084728	0.5359206091455541
0	100	0.01386793487399507	0.7304609364663149	0.6480159106639183	0.41084065861637076
0	100	0.36082263352323185	0.19255932163030642	0.5832995411454666	0.4231199512157455
1	100	0.24434117994194782	0.40654813181749727	0.5760772294720323	0.5689696349004272
2	100	0.2640113555206345	0.9101757126052573	0.1468593731027389	0.6202184617895963
0	101	0.6445492878877913	0.9393752647865824	0.8782811206461665	0.06155760291074741
0	101	0.0391478117208669	0.8289305808544266	0.15732825570638398	0.810192132529246
0	101	0.41636558182363037	0.06300000298506869	0.19768374800057087	0.8448096990814711
1	101	0.7191740187766613	0.945746842262128	0.8570465518925168	0.2125836005675651

$ LightGBM/lightgbm task=predict input_model=lgbm_model.txt data=tmp.tsv header=true output_result=pred_tmp.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

$ head pred_tmp.txt 
-0.02745108988247158
-0.39943097926145144
0.63986234187669611
1.0541387019913457
1.6918502361811527
-1.0965348952564287
0.81806604138389494
-1.1307052283260748
-0.97471278396427918
1.3047786665317376

$ head drop_label.tsv 
qid	f1	f2	f3	f4
100	0.13835814976295646	0.4402769613464669	0.946869449084728	0.5359206091455541
100	0.01386793487399507	0.7304609364663149	0.6480159106639183	0.41084065861637076
100	0.36082263352323185	0.19255932163030642	0.5832995411454666	0.4231199512157455
100	0.24434117994194782	0.40654813181749727	0.5760772294720323	0.5689696349004272
100	0.2640113555206345	0.9101757126052573	0.1468593731027389	0.6202184617895963
101	0.6445492878877913	0.9393752647865824	0.8782811206461665	0.06155760291074741
101	0.0391478117208669	0.8289305808544266	0.15732825570638398	0.810192132529246
101	0.41636558182363037	0.06300000298506869	0.19768374800057087	0.8448096990814711
101	0.7191740187766613	0.945746842262128	0.8570465518925168	0.2125836005675651

$ LightGBM/lightgbm task=predict input_model=lgbm_model.txt data=drop_label.tsv header=true output_result=pred_drop_label.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction

$ head pred_drop_label.txt 
-0.02745108988247158
-0.39943097926145144
0.63986234187669611
1.0541387019913457
1.6918502361811527
-1.0965348952564287
0.81806604138389494
-1.1307052283260748
-0.97471278396427918
1.3047786665317376
```

File: src/application/predictor.hpp (hunk 1 above)
Comment (guolinke) [reply src/application/predictor.hpp]: too avoid duplicated feature names

File: src/io/parser.cpp (hunk 2 above)
Comment (guolinke) [reply src/io/parser.cpp]: yes, this output is designed for the file without the header.
When there is no header, we need to exclude the label column, otherwise, we will read the wrong features. Provide this output is to let the user confirm whether we process his input correctly or not.

When there is a header, we don't need to exclude the label column, as we can get feature by its name.

**Comment by araman0** [comment]
@guolinke I've confirmed it outputs same predictions. thx!
```
$ LightGBM/lightgbm task=predict input_model=lgbm_model.txt data=tmp.tsv header=true output_result=pred_tmp.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction
$ head pred_tmp.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743
$ LightGBM/lightgbm task=predict input_model=lgbm_model.txt data=shuffle1.tsv header=true output_result=pred_shuffle1.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction
$ head pred_shuffle1.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743
$ LightGBM/lightgbm task=predict input_model=lgbm_model.txt data=shuffle2.tsv header=true output_result=pred_shuffle2.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction
$ head pred_shuffle2.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743
$ LightGBM/lightgbm task=predict input_model=lgbm_model.txt data=shuffle3.tsv header=true output_result=pred_shuffle3.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction
$ head pred_shuffle3.txt 
-0.67235347824716607
-0.32698080395337359
-0.28923179728330589
0.18131331367689701
1.018185089266975
-1.2743996252961152
-1.3109041864684552
-0.81249028101368681
-0.27020354133159391
0.12807112089932743

$ LightGBM/lightgbm task=predict input_model=lgbm_ignore_model.txt data=tmp.tsv header=true output_result=pred_tmp_ignore.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Info] Finished prediction
$ head pred_tmp_ignore.txt
-0.43058259683609235
-0.098525361939025474
-0.2048474171242694
0.026815875041871856
0.94411773547211675
-0.89330324800246408
-1.3645662587572376
-0.5720641564103417
-0.46146592181818258
0.069007612700339171
$ LightGBM/lightgbm task=predict input_model=lgbm_ignore_model.txt data=drop_column.tsv header=true output_result=pred_drop_column_ignore.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Warning] Feature (f4) is missed in data file. If it is weight/query/group/ignore_column, you can ignore this warning.
[LightGBM] [Info] Finished prediction
$ head pred_drop_column_ignore.txt
-0.43058259683609235
-0.098525361939025474
-0.2048474171242694
0.026815875041871856
0.94411773547211675
-0.89330324800246408
-1.3645662587572376
-0.5720641564103417
-0.46146592181818258
0.069007612700339171
$ LightGBM/lightgbm task=predict input_model=lgbm_ignore_model.txt data=add_column.tsv header=true output_result=pred_add_column_ignore.txt
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished initializing prediction, total used 100 iterations
[LightGBM] [Warning] Feature (f4) is missed in data file. If it is weight/query/group/ignore_column, you can ignore this warning.
[LightGBM] [Info] Finished prediction
$ head pred_add_column_ignore.txt
-0.43058259683609235
-0.098525361939025474
-0.2048474171242694
0.026815875041871856
0.94411773547211675
-0.89330324800246408
-1.3645662587572376
-0.5720641564103417
-0.46146592181818258
0.069007612700339171
```
