### PR TITLE
[python-package] clarify max_depth warning and limit when it is emitted

### LINKED ISSUE #2898: [doc] Warning message says "you didn't set num_leaves" even if I explicitly set num_leaves=31
## Environment info

Operating System: Ubuntu 18.04.3 LTS

CPU/GPU model: Not sure (running in AWS EC2)

C++/Python/R version: GCC 7.5/Python 3.7.5

LightGBM version or commit hash: 6b6709

## Error message

[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves

## Steps to reproduce

Fit any model with num_leaves = 31 and max_depth >= 5

At line 307 of src/io/config.cpp, the check for whether to show the warning can't tell whether num_leaves is 31 because that's the default or because 31 was explicitly passed. The text "you didn't set num_leaves" in the message is confusing if I did explicitly set num_leaves to 31.

### LINKED ISSUE #5734: Confused about 2^max_depth > num_leaves warning
I followed the parameter tuning guide at https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html, which says 

> 1. num_leaves. This is the main parameter to control the complexity of the tree model. Theoretically, we can set num_leaves = 2^(max_depth) to obtain the same number of leaves as depth-wise tree. However, this simple conversion is not good in practice. The reason is that a leaf-wise tree is typically much deeper than a depth-wise tree for a fixed number of leaves. Unconstrained depth can induce over-fitting. **Thus, when trying to tune the num_leaves, we should let it be smaller than 2^(max_depth).** For example, when the max_depth=7 the depth-wise tree can get good accuracy, but setting num_leaves to 127 may cause over-fitting, and setting it to 70 or 80 may get better accuracy than depth-wise.

However, when I set max_leaves = 31 and max_depth = 8 explictly, I keep getting the warning message:

> [LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).

The warnings actually do not make sense since num_leaves = 31 is good enough for my model and I set max_depth = 7,8,9 to prevent overfitting. For example, if I follow the warning message and set max_depth = 4, in my opinion max_depth is no longer a valid hyperparameter since only 16 leaves can be grown. 

I really wonder if I misunderstand something in your manual or the warning itself is misleading. I am looking forward to your reply.

Thanks.

### PR DESCRIPTION
**Pull request by jameslamb**
fixes #2898
fixes #5734

Modifies a warning that has historically been confusing for some LightGBM users. @shiyu1994 explained it very well in https://github.com/microsoft/LightGBM/issues/2898#issuecomment-1002860601:

> *The warning message is actually saying: "you forget to set `num_leaves`, but you've set `max_depth`"...because LightGBM has a default `num_leaves=31`, the warning message reminds the user to set `num_leaves` accordingly when setting `max_depth`.*

This PR proposes an implementation of @shiyu1994 's proposal from further down in that comment.

> *keep the document unchanged. But in config.cpp... detect whether `num_leaves` is set by user (instead of simply checking whether it is ==31, since user can also set it to 31). And if `num_leaves` is not set but `max_depth` is set, we may produce a warning...*

As a side effect of this change, that also means the warning in question will **never** be raised from the  `scikit-learn` estimators. They always pass `num_leaves` in params, from this keyword argument:

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/python-package/lightgbm/sklearn.py#L463

I think that's ok.  We have the docs in https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html#tune-parameters-for-the-leaf-wise-best-first-tree. I'd rather have the `scikit-learn` estimators not emit this warning than take on the added complexity that'd be required to detect whether or not `num_leaves` was explicitly provided in the constructor keyword args.

## Notes for Reviewers

I would really like a review from @shiyu1994, to be sure I've interpreted https://github.com/microsoft/LightGBM/issues/2898#issuecomment-1002860601 correctly.

Would also appreciate feedback from any of the people involved in the previous discussions about this one whether this new warning is clearer.

```text
[Warning] Provided parameters constrain tree depth (max_depth=8) without explicitly setting 'num_leaves'.
This can lead to underfitting. To resolve this warning, pass 'num_leaves' (<=256) in params.
Alternatively, pass (max_depth=-1) and just use 'num_leaves' to constrain model complexity.
```

cc @bfrobin446 @AlbertoEAF @dxyzx0 @aEgoist @memeplex @Wang-Yu-Qing @Cat2Li

### CODE REVIEW

File: include/LightGBM/config.h [hunk 1]
```diff
@@ -1134,7 +1134,7 @@ struct Config {
   static const std::string DumpAliases();
 
  private:
-  void CheckParamConflict();
+  void CheckParamConflict(const std::unordered_map<std::string, std::string>& params);
```
Comment (jameslamb) [inline include/LightGBM/config.h:1137]: `params` here contains the content of what was passed through by the used (with aliases already resolved). So it can be used to differentiate between "user code passed `num_leaves=31`" and "`num_leaves=31` because that's the default and user didn't pass any value for it".

File: src/io/config.cpp [hunk 2]
```diff
@@ -356,14 +356,24 @@ void Config::CheckParamConflict() {
...
     }
   }
-  // Check max_depth and num_leaves
-  if (max_depth > 0) {
+
+  // max_depth defaults to -1, so max_depth>0 implies "you explicitly overrode the default"
+  //
+  // Changing max_depth while leaving num_leaves at its default (31) can lead to 2 undesirable situations:
+  //
+  //   * (0 <= max_depth <= 4) it's not possible to produce a tree with 31 leaves
```
Comment (borchero) [inline src/io/config.cpp:364]: Do we also want to emit a warning for this case actually?

File: src/io/config.cpp [hunk 3]
```diff
@@ -356,14 +356,24 @@ void Config::CheckParamConflict() {
...
+  if (max_depth > 0 && (params.count("num_leaves") == 0 || params.at("num_leaves").empty())) {
     double full_num_leaves = std::pow(2, max_depth);
-    if (full_num_leaves > num_leaves
-        && num_leaves == kDefaultNumLeaves) {
-      Log::Warning("Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves."
-                   " (num_leaves=%d).",
-                   num_leaves);
+    if (full_num_leaves > num_leaves) {
+      Log::Warning("Provided parameters constrain tree depth (max_depth=%d) without explicitly setting 'num_leaves'. "
+                   "This can lead to underfitting. To resolve this warning, pass 'num_leaves' (<=%.0f) in params. "
```
Comment (borchero) [inline src/io/config.cpp:373]:
```suggestion
                   "This can lead to underfitting. To resolve this warning, explicitly pass 'num_leaves' (<=%.0f) in params. "
```

File: tests/python_package_test/test_basic.py [hunk 4]
```diff
@@ -877,3 +877,57 @@ def test_feature_names_are_set_correctly_when_no_feature_names_passed_into_Datas
         data=np.random.randn(100, 3),
     )
     assert ds.construct().feature_name == ["Column_0", "Column_1", "Column_2"]
+
+
+# NOTE: this intentionally contains values where num_leaves <, ==, and > (max_depth^2)
+@pytest.mark.parametrize("max_depth,num_leaves", [(-1, 3), (-1, 50), (5, 3), (5, 31), (5, 32), (8, 3), (8, 31)])
```
Comment (borchero) [inline tests/python_package_test/test_basic.py:883]: [nit] I prefer to differentiate between parameters more clearly :smile:

```suggestion
@pytest.mark.parametrize(("max_depth" ,"num_leaves"), [(-1, 3), (-1, 50), (5, 3), (5, 31), (5, 32), (8, 3), (8, 31)])
```

**Review by borchero — COMMENTED** [review]
Makes sense to me! A few small comments... :smile:

File: tests/python_package_test/test_basic.py (hunk 4 above)
Comment (jameslamb) [reply tests/python_package_test/test_basic.py:883]: sure, I'm indifferent.

File: src/io/config.cpp (hunk 3 above)
Comment (jameslamb) [reply src/io/config.cpp:373]: I disagree with this one, I don't think "explicitly" adds any information here.

File: src/io/config.cpp (hunk 2 above)
Comment (jameslamb) [reply src/io/config.cpp:364]: I don't think we should.

In this case, LightGBM is going to try to fit a full depth-wise tree.

So all these combinations would be the same:

```text
max_depth=4, (omitted num_leaves)
max_depth=4, num_leaves=31
max_depth=4, num_leaves=21
max_depth=4, num_leaves=16
```

So yeah, if you don't understand that you might end up wasting some cross-validation runs on parameter combinations that will generate the same model, but you won't get a worse fit.

I think it's the right balance to generally defer figuring those things out to users' evaluation setups.

I think the *new* warning added in this PR is a worthwhile addition because it tells users about a situation that is non-obvious and which could *substantially* affect performance. e.g. if you set `max_depth=8` and omit `num_leaves`, you have 256 leaves available to you and are only using up to 31 of them... that's a pretty big gap, that isn't obvious.

**Comment by shiyu1994** [comment]
I'll review this tomorrow. Thanks.

File: src/io/config.cpp (hunk 2 above)
Comment (borchero) [reply src/io/config.cpp:364]: All right, fair enough! :+1:

**Review by borchero — APPROVED** [review]
LGTM! (modulo linting CI job :smile:)

**Comment by jameslamb** [comment]
@shiyu1994 could you please review this this week?

**Review by shiyu1994 — APPROVED** [review]
Looks good to me. Thank you for the change.
